lightning/bolts

03-transactions.md

I may have missed something, but I don't see how the 'to-local' output can be spent by a penalty tx when a revoked commit tx is published: it seems that its script should be the same as the htlc timeout/htc success tx output script ?

'to-local output': add revocation key

---

02-peer-protocol.md
03-transactions.md

Interestingly, too-high a fee level is a problem again, since it's applied to second-stage txs and the HTLC holder has to pay that (not necessarily the funder).

BOLT 02/03: Add fee calculation details.

---

01-messaging-crypto-and-init.md

Fixed typos

---

00-introduction.md
01-messaging-crypto-and-init.md
02-peer-protocol.md
03-transactions.md
04-onion-routing.md
05-onchain.md
06-irc-announcements.md
07-routing-gossip.md
README.md

Please explicitly acknowledge!  @cdecker @Roasbeef @sstone @pm47 @josephpoon @adiabat @BitfuryLightning 
Closes: #2

Add CC-BY.

---

07-routing-gossip.md

This lets us gain 7 more bits, but also as Christian points out, you need
to remember the padding for re-broadcast since the signature covers it.

BOLT 7: Use a flags word, not padding.

---

01-messaging-crypto-and-init.md
02-peer-protocol.md
07-routing-gossip.md
tools/extract-formats.py

You made me write python!  Shame on you!
This doesn't enforce that total message length meet alignment constraints!  C implementers beware that they will have junk at the end of their structures, since we have some odd lengths.

tools/extract-formats.py: produce structure definitions and check alignment

---

03-transactions.md

I forgot to add in the amount+scriptsize overhead for each HTLC.

BOLT 3: Fix fee calculation.

---

01-messaging-crypto-and-init.md

Major changes:
1. Move crypto first, then cover contents
2. Use "lightning messages" explicitly to refer to upper layer, use
"packet" in the one case where we refer to the whole thing.
3. Collapse "Transport Message Exchange" and "Protocol Message Encapsulation"
into "Lightning Message Specification" which already contains much overlap.
Minor changes:
1. Put the big-endian requirement in the general overview, since the crypto
layer uses that too.
2. Say "is" instead of "should be" encrypted: it's not an option.
3. Note why we separate local and global features.

BOLT 01: reorganize, tighten nomenclature.

---

03-transactions.md

Hi, I come up with slightly different estimation for commitment transaction weight. Would you consider to correct my numbers and add more detailed description? I think it might be helpful especially if you read the spec at first time.

BOLT 3: add more detailed commitment transaction estimation

---

03-transactions.md

Based upon @AndrewSamokhvalov PR #26.

Better calcs

---

02-peer-protocol.md

From an implementor's point of view, I think the `update_fee` message is much closer to other `update_*` messages than to channel setup or teardown, and belongs to the Normal operation section. `update_fee` messages will be queued along with htlc-related messages, and applied in order when signing a new commitment.
NB: a consequence of this is that the `type` of the message changes from `37` to `134`.
edit:
Actually I wonder if we should reserve types:
- `32`-`127` to channel creation, establishment, and in the future: cash in, cash out, reanchoring, ...
- `128`-`255` to commitment update (htlc, fees, signatures)
But I am not sure what the rationale was for the current logical grouping?

BOLT 2: Move update_fee message from 'Channel Establishment' to 'Normal Operation'

---

01-messaging.md

Related to #38.
@cdecker can you please acknowledge this? thanks

BOLT 1: Changed logical grouping of messages

---

02-peer-protocol.md
03-transactions.md

Same contents as #66, just with fewer commits

BOLT 3: Add test vectors for transactions (take 2)

---

02-peer-protocol.md
04-onion-routing.md
07-routing-gossip.md

OK, this took way longer than I thought, but I think this works. Adds onto #61 and closes #53

Detailed error format

---

02-peer-protocol.md

revoke-and-ack is already 133.

BOLT 2: fix duplicate numbers.

---

00-introduction.md
08-transport.md

This is my first PR on github. Please be lenient with me :-)

Minor fixes in message parsing indexes and spelling

---

02-peer-protocol.md

Here are few things I noticed while reading the document.

Bolt 02: minor fixes

---

02-peer-protocol.md

This follows a discussion in the comment section of #106.
Credits go to Rusty

BOLT 2: added requirements on htlc forwarding

---

02-peer-protocol.md

We didn't actually say what it does :)

BOLT 2: document requirements of max-htlc-value-in-flight-msat

---

02-peer-protocol.md

It was never mentioned, but fulfilling a timedout HTLC means a race
between timing out and fulfilling, which is bad.

BOLT 2: require that we don't fulfill close to timeout either.

---

01-messaging.md

BOLT 1: max requested pong length is 65531, not 65533, add rationale.

---

01-messaging.md

BOLT1: Fix brackets

---

02-peer-protocol.md
07-routing-gossip.md

From the mailing list:
https://lists.linuxfoundation.org/pipermail/lightning-dev/2017-May/000707.html

ZmnSPCxj typo fixes

---

02-peer-protocol.md
03-transactions.md
05-onchain.md
07-routing-gossip.md

More trivial things I missed with my simple regex search, plus a name consistency update.

Even more underscores

---

05-onchain.md

We talk about failing a channel, or channels, but we never spelled
out what a node does in that case.

BOLT 5: define what "failing a channel" means.

---

02-peer-protocol.md

This is just a subset of #164 while we discuss the normal-state retransmission revision.
I think this reflects consensus?  I included the error retransmission because the text was entangled, and it seems pretty sensible.

Error retransmit and opening retransmit revision.

---

01-messaging.md
09-features.md

I believe the final result of this is better, and hopefully understandable!  If acked, I will squash into one patch and apply.

Rework #156

---

tools/extract-formats.py
tools/structured.py

This PR replaces #198 since I was unable to rebase and push onto the original branch (Allow edits from maintainers is off or pushing to someone else's `master` is not allowed).
It includes the structured format from @ysangkok and I took the liberty of cleaning both scripts up a bit.

Script for extracting structured protocol messages (replaces #198)

---

11-payment-encoding.md

Allows us to put multiple routes in; there was previous confusion.
Closes: #215

BOLT 11: change `r` to hold multiple entries.

---

11-payment-encoding.md

BOLT 11: signature is of single SHA256, not double.

---

02-peer-protocol.md
05-onchain.md

This is what happens when you actually implement on-chain HTLC handling; I found some gaps in the spec.  No real changes here, though.

Onchain htlc clarifications

---

11-payment-encoding.md

Reported-by: Andy Schroder <info@AndySchroder.com>

BOLT 11: p is payment hash, not preimage (in annotated examples).

---

05-onchain.md

Attempts to clarify the weight calculation of penalty transactions, and makes sweeping the `to_remote` output optional without breaking any existing constraints. Assuming these figures are correct, the decision to sweep the `to_remote` _does not_ change the current unidirectional limit of 483 HTLCs.  Thus, the option to do so can be made independently by either party/implementation. I've currently specified this as MAY, but we could introduce a stronger modifier if we think that's appropriate.
The previous equation used to calculate `max_num_htlcs` slightly underestimated the theoretical maximum weight, since non-witness data was treated as 1:1 with witness data.  Ultimately, this had no effect on the computed results, but figured we should be more specific here for the purpose of …

BOLT 5: clarifies penalty txn weight calculation

---

05-onchain.md

Nasty corner case which I got wrong; we can fulfill but then we risk
a reorg removing it.  And anyway, fulfilling reveals that we are
the endpoint in practice.

BOLT 5: don't fulfill offered HTLCs if peer not committed to it.

---

05-onchain.md

BOLT 5 only talks in terms out HTLC outputs, but not all HTLCs have outputs.
HTLCs which are dust for both sides are easy, but others require the
commit tx to be buried before we can consider the HTLC failed.

BOLT 5: requirement to fail HTLCs which don't have outputs in the commit tx

---

05-onchain.md

BOLT 5: "MUST spending" -> "MUST spend"

---

11-payment-encoding.md

BOLT 11: depending in -> depending on.

---

04-onion-routing.md

This is a partial response to #250. Reordering the HMAC and Encrypt
steps do not give us much, but we might want to hide the route
length. So we suggest that the node should continue unwrapping until
the maximum route length of 20 is reached.

BOLT04: Clarify that nodes should continue to unwrap the error onion

---

.aspell.en.pws
00-introduction.md

And lets never mention it again

---

02-peer-protocol.md
04-onion-routing.md
07-routing-gossip.md

Deriving cltv and example

---

01-messaging.md
02-peer-protocol.md
05-onchain.md
tools/extract-formats.py

Our first optional field.  I didn't bother specifying a feature bit, but we could.
After some consideration, I think this is better than the original #209 proposal.

Send secret on reestablish

---

05-onchain.md

added permalink to reference implementation code for coinbase maturity check.

BOLT #5: Added permalink as reference for one of FIXMEs

---

02-peer-protocol.md

Trivial and obvious, but let's be explicit!

Extra open channel requirements

---

.travis.yml
02-peer-protocol.md
09-features.md
tools/extract-formats.py

The first commit is taken from #240 the rest are new based on #243

Commit to scriptpubkey as an option

---

.aspell.en.pws
.copy-edit-stylesheet-checklist.md
00-introduction.md
01-messaging.md
02-peer-protocol.md
03-transactions.md

Update stylesheet guidelines and apply updates to BOLT 0, 1, 2.
Complete first pass copy-edit on BOLT 3.

Copy-edit Bolts

---

05-onchain.md

HTLC maximum limit : 511 --> 483
https://github.com/lightningnetwork/lightning-rfc/commit/0d7cf77970e53e366c878310627ce3fc45858015

BOLT5: fix htlcs max

---

00-introduction.md
02-peer-protocol.md

This is PR 289, with the suggested fixes.  The branch for that one was deleted, so needs to be a new PR apparently.
Closes: #289

PR-289: The Revenge

---

11-payment-encoding.md

This would have saved me a lot of time and pain. Sure, I should have realized that the document says something paradoxical (signature of the data part.... but the data part includes the signature..... so I should have guessed it meant "excluding the signature"...)
Explicit mention of the signature part might help people. Might not. But helps to be explicit.

BOLT#11 Explicitly mention signature removal + Add signature related data in examples

---

04-onion-routing.md

-Separate out requirements into their own sections.
-Add a couple [FIXME:] tags.

Bolt4 copy edit

---

09-features.md

I regularized the descriptions in the localfeatures table, so keep a careful eye on the accuracy of those. Otherwise, fairly standard editing in this very short section.

BOLT-09 Edits

---

tools/spellcheck.sh

Fix typo in spellchecker ¯\_(ツ)_/¯

---

10-dns-bootstrap.md

Mostly simple copy-editing and clarity, though I have one query on address types before I can close this out.

BOLT-10 Edits

---

.aspell.en.pws
05-onchain.md

First pass copy edit of second half of BOLT 5

BOLT5 copy edit - part 2

---

02-peer-protocol.md
03-transactions.md
04-onion-routing.md
07-routing-gossip.md
08-transport.md
09-features.md
10-dns-bootstrap.md
11-payment-encoding.md

Remove trailing whitespace

---

02-peer-protocol.md

BOLT 2: order closing-signed negotiation by making funder send first.

---

03-transactions.md

This is my final first-pass BOLT. Some grammar changes, some remote/local additions, a few questions.

BOLT-3 Edits

---

02-peer-protocol.md

BOLT02: Add rationale for 2^24 satoshi per channel limit

---

07-routing-gossip.md

Complete first pass copy edit of second half of BOLT 07.
- imposed 'origin/final node' terminology
- one FIXME question

BOLT 07: copy edit, part 2

---

02-peer-protocol.md
tools/extract-formats.py
tools/structured.py

correct feature flagged message fields syntax, update structured.py to support feature flagged fields, print to right output in extract-formats.py

Feature flagged message field updates

---

07-routing-gossip.md

BOLT#00
> hash is not reversed

BOLT07: `chain_hash` is reversed

---

04-onion-routing.md

the amount paid is less than the amount expected.

BOLT04: add return code

---

11-payment-encoding.md

This supersedes PR #382, which went stale.

New take on PR 382

---

08-transport.md

Finally finished second pass copy edit (after @shannona's) of BOLT 08, to bring it inline with the stylesheet guidelines.

Bolt8 copy edit

---

10-dns-bootstrap.md

Add missing space in command line example.

Add missing space in command-line example

---

08-transport.md

1 message = 2 encryptions.
Fixes: #403

BOLT 8: clarify rotation frequency.

---

09-features.md

Copy edit for clarity and consistency with stylesheet guidelines.
Continuing on with copy editing the remaining bolts, after a bit of a hiatus.

BOLT 09 copy edit

---

03-transactions.md
07-routing-gossip.md

This PR fixes broken links in BOLT 3 and BOLT 7.

BOLT 3/BOLT 7: Fix broken links.

---

07-routing-gossip.md

Max capacity in channel update

---

04-onion-routing.md

BOLT 4: final_incorrect_htlc_amount should be 64-bits.

---

07-routing-gossip.md

Uncertain if this is best place to describe human-readable format, but, this section is what describes the components of the scid.

07-routing-gossip.md: Describe standard human-readable format for short channel ID.

---

00-introduction.md
02-peer-protocol.md

Reading through BOLT 2, I noticed a couple of things that could make it easier to understand. There's a few things I've added that I'm not certain are correct, I've annotated them with a comment.

BOLT 2: readability edits

---

.copy-edit-stylesheet-checklist.md
11-payment-encoding.md

- clarify purpose of stylesheet
- add spellchecker execution instructions to stylesheet
- bring BOLT 11 inline with stylesheet guidelines
Whew...finally done editing all the BOLTs! Won't mess with them anymore, promise.

BOLT 11: Copy edit

---

02-peer-protocol.md

BOLT 2: `payment hash` not `revocation hash`.

---

02-peer-protocol.md

Fix wording in introduction of chapter `Channel Establishment` about `funding_signed` message.

BOLT 2: fix sentence in introduction of chapter `Channel Establishment`

---

05-onchain.md

Make `## HTLC Output Handling: {Local,Remote} Commitment, Local Offers` look similar, choosing the best parts of each.

BOLT 5: Homogenize Local/Remote Commitment

---

00-introduction.md

Added Internal Link for Readability in Markdown to Glossary. Notice the LN song as well ;)

Added Internal Link to Glossary

---

11-payment-encoding.md

I guess this clarification isn't necessary since, if I understand it correctly, it is said elsewhere.
Totally fine with me if this is rejected.

BOLT11: Clarification on n field

---

.aspell.en.pws
.travis.yml
CONTRIBUTING.md

Additions and feedback welcome!

CONTRIBUTING.md: first draft of how to write and change spec.

---

01-messaging.md

fix <id> tag

---

03-transactions.md

... to make it consistent with the `where_to_put_secret` above.

Fix a typo in `insert_secret` pseudo code

---

.aspell.en.pws
09-features.md

See #824. This PR only reserves the feature bits.

bolt-09: reserve feature bits for option_anchors_zero_fee_htlc_tx

---

03-transactions.md

BOLT 3: add a missing Otherwise, don't SHOULD "be".

---

.aspell.en.pws
02-peer-protocol.md

Since Travis died, we don't get CI to check these any more :(

Fix typo and aspell list.

---

tools/extract-formats.py

6fee63fc342736a2eb7f6e856ae0d85807cc50ec made `htlc_maximum_msat` compulsory, which was the last "optional" field.  All future options will be TLVs, so we never need to parse the "] (optionxxx)" format for fields again.
We allow options for messages, but only for documentation (we have some messages which are only for `gossip_queries`), so we don't put it in the output.
Here's the before/after diff of the output for all the spec files:
```diff
--- /tmp/before	2023-04-27 14:21:07.417170213 +0930
+++ /tmp/after	2023-04-27 14:19:39.184573086 +0930
@@ -273,7 +273,7 @@
msgdata,channel_update,fee_base_msat,u32,
msgdata,channel_update,fee_proportional_millionths,u32,
msgdata,channel_update,htlc_maximum_msat,u64,
-msgtype,query_short_channel_ids,261,gossip_queries …
```

tools: remove option handling now last optional field was removed.

---

02-peer-protocol.md

`comitting` should have two `t`'s

Fix broken link in BOLT-2

---

tools/bolt3-bitcoind-test.sh

fix typo in tools/bolt3-bitcoind-test.sh

chore: fix typo in tools/bolt3-bitcoind-test.sh
