lightning/bolts

02-peer-protocol.md, 03-transactions.md
After much discussion with @adiabat  and @Roasbeef , I think we have something
which is nicely outsourcable, and yet not insanely complex.
=> BOLT 2/3: watcher-compatible key derivation.

02-peer-protocol.md
Fixed inconsistency in naming (see comments of PR #7)
=> minor: close_signature -> closing_signed

02-peer-protocol.md, 07-routing-gossip.md
Contents stolen from @cdecker 's draft, but tightened requirements and split into three messages.
I added bitcoin-to-node cross-signing, require both sigs for announcing a channel, expanded expiry from 1 to two bytes to match BOLT #2.  I think the result is pretty simple, though I can see us later switching to schnorr and having a bulk-update message.
=> BOLT #7: More complex proposal, using three separate message types.

02-peer-protocol.md
We need to supply a pair (a signature using our bitcoin key which signs the
node id, and a signature using our node key which signs the announce message),
and the length was wrong.  Move them to make alignment nicer, too (though
it probably doesn't matter, they're 4-byte aligned everywhere else).
=> BOLT 2: fix funding_locked announcement signatures.

02-peer-protocol.md
If someone used an output > 255, the rest of the protocol would break.
=> BOLT 2: Only single byte for channel-index.

02-peer-protocol.md
```
A                                B
|                                |
|       (1) open_channel         |
|------------------------------->|
|                                |
|       (2) accept_channel       |
|<-------------------------------|
|                                |
|      (3) funding_created       |
|------------------------------->|
|                                |
|       (4) funding_signed       |
|<-------------------------------|
```
B needs A's `first-per-commitment-point` to compute the signature that B is supposed to return in step (4).
On a related note, I am not sure why A includes his signature in `funding_created`. At first I thought the reason for this is that the first commitment transaction can pay both parties, because of the possibility to have a …
=> Adding a first-per-commitment-point field to open_channel

01-messaging-crypto-and-init.md, 02-peer-protocol.md, 05-onchain.md
Since our cryptopacket limits us to 2 bytes, and since people will send 1-message-per-crypto-packet and nobody will test the multiple-messages-in-one-cryptopacket code, let's just restrict to 64k messages.
1. Make cryptopacket length not include the HMAC, so we can actually send
64k messages.
2. Remove len prefix from packet, add padding to restore alignment.
3. Change message internal lengths/counts from 4 to 2 bytes, since more
is nonsensical anyway, and this removes a need to check before allocating:
- init feature bitfield length
- error message length
- shutdown scriptpubkey length
- commit_sig number of HTLC signatures
- revoke_and_ack number of HTLC-timeout signatures
4. Also change max-num-htlcs to a single byte, which ensures that commit_sig
will always be under 64k (max around …
=> [RFC] BOLT 1, BOLT 2, BOLT 5: 2-byte lengths everywhere.

01-messaging.md, 08-transport.md
The separation between between framing, type and payload HMAC, while
logically nice, make it quiet hard to get a complete picture. Merging
these parts results in a clearer picture of how packets look like. I
also wrote a small intro to get a quick overview. The reader can then
drill down into the specifics of the individual components.
=> Splitting BOLT01 into messaging and transport specs

02-peer-protocol.md, tools/extract-formats.py
They're really a blob of bytes, and we weren't aligning them correctly in
two cases anyway.  This gets rid of gratuitous padding, too.
=> BOLT 2: remove attempts to align signatures.

01-messaging.md, 02-peer-protocol.md
Makes more sense I think, since some messages are described in BOLT #1.
=> Moved msg type description from BOLT#2 to BOLT#1

03-transactions.md
These were generated (and recovery tested) by the command-line tool at:
https://github.com/rustyrussell/ccan/tree/master/ccan/crypto/shachain/tools
=> BOLT 3: Add test vectors for per-commitment-secret generation

02-peer-protocol.md
Specifying that the `onion-routing-packet` commits to the
`payment-key` by setting the associated data. This avoids replay
attacks and specifying it here keeps the onion-routing spec clean.
=> onion: Specifying `payment-key` commitment in onion

04-onion-routing.md
FIPS 198 is based on RFC 2104, but further restricts the hashing
functions to the SHA-family, so this is a bit redundant, but my hope
is to avoid confusion about whether there is a difference.
Thanks @rustyrussell for pointing this one out.
=> bolt04: Add reference to RFC 2104 in onion routing spec

04-onion-routing.md, 08-transport.md
You should probably be using this library anyway, so let's use their
ECDH style.
Closes: #49
=> BOLT 4, BOLT 8: use libsecp256k1-style ECDH.

07-routing-gossip.md
Fabrice, if you approve, please merge.  Everyone seemed happy with the idea of dropping the nul byte terminator, too.
=> BOLT 7: fix 21-byte limit typo, allow alias to use all characters.

08-transport.md
They're salt and ikm respectively (using language from RFC5869).
=> BOLT 8: clarify the hkdf args.

02-peer-protocol.md, 03-transactions.md
- change outputs limit to 252 as more would mean `output-index` > 1 byte
- remove `0` from the funding output script as it is not part of a normal 2-of-2 multisig script
I believe these two corrections are appropriate.
BOLT02 says: "The `output-index` can only be 1 byte.." , this means compact size int up to 0xFC, or 252.
BOLT03 describes the "Funding Transaction Output" as a P2WSH of a 2-of-2 multisig redeemscript of the two commit keys' pubkeys.
This is just a normal 2-of-2 multisig, so `0` isn't really used.
=> Fix outputs limit and funding output script

04-onion-routing.md
So here's a first stab at specifying the format and forwarding related error conditions around the per-hop-payload that's now a part of the Sphinx packet. 
The current proposed format is: `[1:realm][8:amt_to_forward][2:incoming_cltv_value][9:unused_for_v0]`. Details surrounding the exactly meaning and cross-validation of the payload contents can be found within the sole commit within this PR. 
I'm a bit conflicted about exactly _where_ in the specs the format+handling specification should go. Currently, within the PR I've included it within `BOLT04`. However, the semantics kinda of leak into `BOLT02` as improper values (payload doesn't match the HTLC) within the `per-hop-payload` may result in HTLC failure messages. Also in order to validate the information within the `per-hop-payload` …
=> BOLT04: specify per-hop-payload format

07-routing-gossip.md
This lets us have both IPv4 and IPv6 (and Tor etc in future) address,
while still preserving the ability to add other fields to the message
in future.
=> BOLT 7: allow multiple address descriptors. (Take II)

03-transactions.md
1. HTLCs must be able to pay for their HTLC success/timeout transaction fees
2. The amount in the transaction output for a given HTLC should match the HTLC amount
3. The amount of the HTLC success/timeout transaction should be the HTLC amount minus the transaction fee
4. add examples
=> BOLT 3: fix fee computations

01-messaging.md, 02-peer-protocol.md, 05-onchain.md
This will usually be the commitment tx, but could also be the HTLC
tx.
Reported-by: pm47 <pm.padiou@gmail.com>
=> BOLT 1: recommend full tx in error pkt if signature fails.

01-messaging.md
ASCII character set seems apropriate, since it acts a lowest common
denominator, and who'd stuff emojis in an error message anyway?
Fixes #68
=> BOLT01: Further specifying what it means to be printable

02-peer-protocol.md
Christoper points out that two nodes with aggressive minimum-depth settings
may see different blocks and the protocol requires they close the channel
since their funding_locked messages will disagree.
This can also happen when only one side has an aggressive minimum-depth
setting: if it sends funding_locked referring to a block which is orphaned,
it can't update it.
There are three changes here, two optional.
- Allow sending of an updated funding_locked.  This fixes this case where
one side is on an orphan and uses a v. low minimum-depth.
- Require accepting of an updated funding_locked.
- Allow waiting instead of immediate failure if funding_lock disagrees.
eg. you might wait another block or two to see if one side reorgs.
Reported-by: Christopher Jämthagen
Closes: #73
Signed-off-by: …
=> BOLT 2: allow more leniancy with forks during channel establishment.

02-peer-protocol.md, 04-onion-routing.md
This reduces failure codes to 2 bytes, places them into data itself.
Now we can use the same parsing code for them as we use for normal packets.
BOLT 2 is adjusted to match, and order of args changed to restore sha256
alignment to a nice 8 bytes.
=> BOLT 4: make format of failure codes the same as normal messages.

03-transactions.md
The lower 24 bits of the locktime represents the lower 24 bits of the 
obscured commitment transaction number. If the high byte of locktime 
is always zero, then the locktime value can only assume a maximum 
value of 16,777,215 which is below 500,000,000, meaning the locktime 
will always be compared to block height and not MTP, if enabled.
The most significant byte of the locktime in a commitment transaction
must be set to 0x20. This is to make sure that the locktime value
is always higher than 500,000,000, making it interpreted as a Unix
epoch timestamp, and not a block height. It also makes sure that the
locktime is below the current time, allowing the commitment transaction
to be included in a block
Since the sequence field in the input of the commitment transaction is
used for the …
=> BOLT 3: Fix so commitment transactions are spendable

01-messaging.md, 02-peer-protocol.md
1) Make it clear that `init` needs to be sent every time.
- This means if you upgrade and no longer support an old connection, it's
clear, plus it simplifies the question of re-transmission of `init`.
2) Spell out the retransmission requirements for reconnection.
- We agreed in Milan to simply use retransmit and ignore-dups.
- This needs actual testing by implementations, but this is my best guess
on exactly how far back to retransmit.
=> BOLT 2: Message retransmission and reconnect semantics.

.travis.yml, tools/extract-formats.py
The extraction tool was broken by the recent failure codes patch, since the failure codes description was using the same format that the tool recognized as packet types. This seems to be desirable since it allows us to reuse that tool to create parsers for the failure payloads as well. So I went ahead and fixed the tool to allow packets with no payloads and match masked types as well.
I also added travis-ci (must still be enabled by a repo owner) so that the extraction tool is run against new commits and we get feedback on breakages. Maybe we can expand this to also enforce some spec styles in the future?
=> Fix packet format extraction tool, add failure codes as packets and add CI

03-transactions.md
Not only is it shorter and cheaper, but the rest of the document (including
test vectors and weight calculation) assumed it already.
=> BOLT 3: use P2WPKH instead of P2PKH.

07-routing-gossip.md
Reorders the `channel-id` and `bitcoin-signature-x` fields so that the
signed part of the message is contiguous. Simplifies the signing logic
not to just simple signatures of a contiguous region of the message,
no need to sign signatures, they all commit to the same payload. This
also removes the chicken and egg problem @pm47 reported in #92.
Furthermore it specifies that the signed payload also includes any
future appended fields.
=> bolt07: Simplify signature scheme for `channel_announcement`

04-onion-routing.md
The cltv value in the `per-hop-payload` packet is an absolute value, not a delta, therefore it needs to be encoded on 4 bytes just like `update_add_htlc`.`cltv-expiry`.
To keep the packet length at 20 bytes I removed 2 bytes from the following unused field.
=> BOLT 4: Use 4 bytes for outgoing_cltv_value

00-introduction.md, 02-peer-protocol.md, 07-routing-gossip.md, 09-features.md
So far we did not have any indication on what to do if a node does not
allow announcing the channel and we had a mix of concerns in the
`funding_locked` message, which would also transfer the signatures
needed for the announcement. This is a proposal about splitting the
signatures into their own message, so that simple omission is an
opt-out of announcements, and it does not mix announcement/gossip
stuff into the peer-protocol.
This builds on top of #96. There is some concern that pulling this
message out of the strictly controlled state machine of the channel
lifecycle may have unwanted consequences.
=> BOLT 2&7: Cleaner separation of concerns wrt announcement signatures

07-routing-gossip.md, 09-features.md
Christian assumed first bit was 1, I assumed 0.  And we should generally
assign in pairs (so an optional understanding can later become compulsory),
though for the initial draft it's unnecessary.
By giving names we avoid smearing values over the spec, containing them in
BOLT 9.
=> BOLT 9: assign feature bits in pairs, give them names, clarify position.

07-routing-gossip.md, 09-features.md
Opening a lot of connections results in getting this information a
whole lot of times, so let's add an opt-in flag for the initial dump.
This will cause a conflict with #102, I'll rebase once that is merged.
=> BOLT 7: Added flag for optional initial routing sync dump

03-transactions.md
There were some minor off-by-one errors due to not taking length of constants into account.
=> BOLT 3: Fixed htlc weight calculation

02-peer-protocol.md
=> BOLT 2: specify requirement not to send fulfill until both sides locked in

02-peer-protocol.md
I think `revoke_and_ack` is only acknowledged by `commitment_signed` and `shutdown` because in the following scenario B can send update messages while waiting for revocation):
```
A                                B
|              add               |
|<-------------------------------|
|              sig               |
|<-------------------------------|
| rev                        add |
|---------------  ---------------|
|               \/               |
|               /\               |
|<--------------  -------------->|
|              sig               |
|<-------------------------------|
|              rev               |
|------------------------------->|
```
In our current implementation, `revoke_and_ack` is not even acknowledged by `shutdown` but it might be a little bit far …
=> BOLT 2: revoke_and_ack is not acked by update messages

07-routing-gossip.md, 09-features.md
This follows #109 and Christian's [comment ](https://github.com/lightningnetwork/lightning-rfc/pull/97#issuecomment-277683797) in #97.
I have also renamed `channel_public` to `channels_public`.
=> BOLT 9: Make it clear that 'channel_public' apply to all channels

08-transport.md
We dropped reference 1 and 2 during the split, and the offset
numbering is causing a bit of head-scratching. This renumbers the
reference.
Closes #117
=> BOLT08: Renumbering references

00-introduction.md, 01-messaging.md, 02-peer-protocol.md, 07-routing-gossip.md
At cost of a few extra bytes, this avoids the whole "oops, we were on
a chain fork" problem.
Now we move the announcement_signature exchange to at least 6 confirms,
which makes re-xmit tricky; I resolved that by insisting on reconnect that
we send if we haven't received, and reply to the first one.
The term "channel shortid" wasn't used anywhere, so I removed it; it's
now a gossip-only thing anyway.
Closes: #114
Suggested-by: Olaoluwa Osuntokun <laolu32@gmail.com>
=> BOLT 0,1,2,7: use txout not channel-id for demuxing.

02-peer-protocol.md
In the following scenario B's last `revoke_and_ack` is acknowledged by A's `closing_signed`
```
A                                B
|                                |
|              add               |
|------------------------------->|
|              sig               |
|------------------------------->|
|              rev               |
|<-------------------------------|
|                                |
|              sig               |
|<-------------------------------|
|              rev               |
|------------------------------->|
|                                |
|            shutdown            |
|------------------------------->|
|            shutdown            |
|<-------------------------------|
|                                |
|            fulfill             | …
```
=> BOLT 2: revoke_and_ack is acknowledged by closing_signed

02-peer-protocol.md
Left over from 00a8e97a681e14ece38420a44ac1f276c4b48888, which purported
to change commit_sig -> commitment_signed.
=> BOLT 2: fix remaining commit_sig references.

02-peer-protocol.md
Using the receiver's dust limit implies a naive node can be fooled
(by a peer with massive dust limit) into not getting its own output.
Using our own opens the possibility of creating different transactions,
so we explicitly allow the tractable case, while accepting failure on
the case where disagreement is real.
Closes: #128
Reported-by: Pierre-Marie Padiou
=> BOLT 2: change dust limit for closing to each use their own.

02-peer-protocol.md
As per discussion in #115, we now allow `shutdown` immediately following
`commitment_signed`.
This means that revoke-and-ack doesn't *always* ack the shutdown.  Rather
than specify that a revoke-and-ack which is caused by an update-commit
following the shutdown acknowledges, we leave this unacknowledged until
we actually start closing.
This means we will retransmit it on every reconnect until then.  But
that's not all that wasteful, and fairly robust.
Suggested-by: Pierre-Marie Padiou <pm.padiou@gmail.com>
=> BOLT 2: simplify shutdown constraints.

02-peer-protocol.md
Instead of "ensure the blockchain," it should be "enter the blockchain"
=> BOLT 2: Fix typo

02-peer-protocol.md
This commit adds a `chain-hash` field to message that commences a
funding workflow. This field is used to specify a _target_ chain for the
proposed channel. In order to uniquely identity blockchains in a manner
that doesn't require strict coordination between developers, the genesis
hash of the target chain is used. For channels opened on the Bitcoin
blockchain, the `chain-hash` field should _always_ be set to:
000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f.
Introducing this new field _immediately_ allows nodes within the network
to open a channel within any Satoshi-derived blockchain. Nodes can have
channels open across different blockchains globally, but also have many
channels open across distinct blockchains with the same peer.
=> BOLT 02: add a `chain-hash` field to the `open_channel` msg

02-peer-protocol.md
=> BOLT 2: htlc-cltv must be in blocks.

04-onion-routing.md
The idea of the "SHOULD fail if amount is too much" was courtesy against
overpaying, but that's a bad idea of you value privacy and some vendor has
well-known prices.  Allow a factor of two, at least.
=> BOLT 4: allow more overpaying.

01-messaging.md
Connections between nodes within the network may be very long lived as
payment channels have an indefinite lifetime. However, it’s likely that
for a significant portion of the life-time of a connection, no new data
will be exchanged. Additionally, on several platforms it’s possible that
Lightning clients will be put to sleep without prior warning. As a
result, we use a distinct ping message in order to probe for the
liveness of the connection on the other side, and also to keep the
established connection active.
This commit adds two new control messages to the protocol: `ping` and
`pong`. Their usage within the network is similar to the usage of such
message within other established protocols: `ping` messages specify a
number of bytes to be contained in the payload of a `pong` message, …
=> BOLT 1: introduce `ping` and `pong` control messages

01-messaging.md
Description of message types `0`-`31` needs to be updated after #134.
=> BOLT1: Updated definition of setup messages (minor)

07-routing-gossip.md
This is useful to signal either permanent or temporary channel unavailability. Temporary unavailability may include anything from a connection loss for mobile nodes, or prolonged lack of capacity, though I'd like to discourage the latter. In the case of permanent unavailability this can frontrun the actual closure and tell nodes not to use this channel (-direction) even before they see the on-chain close.
It's more of a heads up, and on-chain settlements should be used for permanent removal.
=> bolt07: Add flag to disable channels temporarily.

04-onion-routing.md
Not doing this check means an inconsistency in behaviour, which could
theoretically allow a hop to probe: if the next hop is the last, it might
not care, but if it's not it will return an error.
=> BOLT 4: error if the final outgoing_ctlv_value is unexpected.

04-onion-routing.md
Should be simple enough: if you fail a channel because it is temporarily unavailable, be nice enough to include the `channel_update` so we can spread the word
=> [Trivial] Include a channel_update with the disable on temporary channel failure

01-messaging.md
The general idea is that starting from when it receives a `funding_created` message, the fundee should reply with the new final `channel_id`. But I think we need to specify better what should happen when things go wrong, because there can be a race under certain conditions. The fundee might send an `error` message with a `temporary_channel_id` to the funder even if the latter already sent a `funding_created` message.
We should probably specify that the fundee should use `temporary_channel_id` before it sends a `funding_signed` message, and `channel_id` after that. This means that it will reply with a `temporary_channel_id` if it is not happy with the proposed funding tx. We ran into this corner case during our tests when there was a huge discrepancy between funder/fundee fee estimates.
=> Acknowledgment of `temporary_channel_id`->`channel_id` switch

02-peer-protocol.md
minimum-depth is no longer in the opening message.
Closes: #157
=> BOLT 2: remove requirement for missing field.

.aspell.en.pws, 07-routing-gossip.md
This commit extends the set of define address descriptor types to
include support for v2 (current-gen) and v3 (next-gen) onion service
addresses. This enables user to run their Lightning nodes as onion
services, only accepting in-bound connections via their onion
addresses. Running a Lightning node behind Tor may serve to boost the
privacy of a user as they no longer need to give away their location
when advertising their node as willing to accept in-bound connections.
The current generation onion service address are widely deployed and
similar looking. They consume 10-bytes of space as they are the SHA-1
hash of a 1024-bit RSA public key. Encoding using base-32, they look
like: v2cbb2l4lsnpio4q.onion.
The next-generation onion services addresses are defined within
prop224_[1]. These …
=> Add support for announcing Tor onion service addresses 

.aspell.en.pws, 04-onion-routing.md
This follows a discussion started in #149. I am only proposing minimal changes, and individual commits are independant:
- https://github.com/lightningnetwork/lightning-rfc/commit/c07b276f7d0d87fc1efbd8f7ea3640a80793b7c1: since #149 added a mandatory `channel_update` message to `temporary_channel_failure`, then this error must have  the `UPDATE` flag
- https://github.com/lightningnetwork/lightning-rfc/commit/142e20769c828e93e7f540c61515cfb218216e91: since `channel_update` is fixed-size, we don't really need to provide its length (credits @cdecker)
- https://github.com/lightningnetwork/lightning-rfc/pull/167/commits/1736ae54960917890e33174838031fd87c79a335: since we already have `amount_below_minimum`, `fee_insufficient`, `incorrect_cltv_expiry` and `expiry_too_soon` errors when incoming …
=> BOLT 4: Fix inconsistencies in error messages

03-transactions.md
This commit attempts to clarify some ambiguity in the way the
revocation key derivation was formerly described. Rather than framing
the description in terms of local vs remote nodes, we instead frame the
description around the _process_ of creating a new commitment
transaction for a remote node.
=> BOLT 3: clarify description of revocation key derivation

02-peer-protocol.md, 04-onion-routing.md, 07-routing-gossip.md
We had 4 byte fields for amounts because people have no ability to assess
risk, and this limited the damage to $70 at a time.
But then that means $1 maximum HTLCs on Litecoin, which isn't enough
for a cup of (decent) coffee.
Rather than have boutique hacks for Litecoin we enlarge the fields now,
and simply have a bitcoin-specific restriction that the upper 4 bytes be 0.
Suggested-by: Olaoluwa Osuntokun <laolu32@gmail.com>
=> BOLT 2,4,7: use 8 bytes for amounts, restrict add_htlc for bitcoin only.

03-transactions.md
They should be HASH160, aka RIPEMD160(SHA256()).
Closes: #179
=> BOLT 3: fix references to RIPEMD160(revocationkey)

02-peer-protocol.md, 07-routing-gossip.md, 09-features.md
This commit gives peers the ability to signal their intent to make a
channel private in the `open_channel` message. This differs from the
current method as now peers are able to create multiple channels with
heterogeneous announcement policies _without_ disconnecting and
re-connecting in-between each channel funding. The prior requirement
for the nodes to re-connect (in order to create a new channel with 
opposite policy of the active) was burdensome and unnecessary.
Additionally, it may not always be the case that upon _connection_ (but 
not yet funding workflow initiation), that a peer knows whether or not it 
wishes to advertise a connected channels. A peer may have originally 
connected just to receive gossip data, but then wishes to establish a 
channel. In this case, the node may …
=> Allow a per-channel rather than per-session policy for announcing opened channels 

.aspell.en.pws, 00-introduction.md, 11-payment-encoding.md, tools/spellcheck.sh
For those who reviewed the previous lightning-payencode draft, the only recent change (modulo bugfixes) is that the timestamp is 35 bits, so it's partitioned nicely in the bech32 encoding.
Also, the payment hash is now a tagged field (in case it changes format), and version has been eliminated (it would be almost impossible to transition to a new version).
=> Bolt 11: Invoice Protocol for Lightning Payments

07-routing-gossip.md
The requirements were updated in 667ca1fdd6d80e9d11a74f01700f07506147c6d8
but not the discussion above.
=> BOLT 7: fix outdated description of channel announce.

07-routing-gossip.md
Explicitly mentions that nodes SHOULD monitor the chain for channel
closes, and that a node MAY be removed if no open channels for that
node remain open.
Also mentions the 2 week lazy pruning we discussed on the call.
Closes #186
=> BOLT7: Add network view pruning

07-routing-gossip.md
This was pointed out by @btcontract in #188: we need to communicate
our forwarding parameters even for private channels since otherwise
the other endpoint cannot use the private channel for incoming
routes. So we also accept `channel_update`s for our own channels even
for channels that were not announced publicly. Adds a bit of special
handling for our own channels in the gossip, but it is needed since
private channels would be completely unusable otherwise.
Fixes #188
=> BOLT7: Allow channel_updates for non-public channels

02-peer-protocol.md
1. You can't eliminate an output and also guarantee a certain fee, so
we need to define exactly how to do this.
Since the output is (presumably) dust, we might as well just discard it
(effectively increasing the fee).  This avoids the peer directly benefiting
from the elimination as well.
2. There are two final commitment transactions, which can be different if each side has a different
dust level.  Make it clear that the max fee must be less or equal to the *base* fee, not the actual
(post-output-elimination) fee.  This means it could be marginally higher than the final fee in theory,
but in practice it's a tiny effect at worst.
=> BOLT 2: closing tx fee clarifications

04-onion-routing.md
Consistency with BOLT 7 makes this much clearer.
Closes: #195
Reported-by: https://github.com/nayuta-ueno
=> BOLT 4: channel_id -> short_channel_id

07-routing-gossip.md, tools/extract-formats.py
Appending new fields to the end of the messages allows us to add new
fields to an existing message, however it does not allow removing
existing fields, e.g., dropping the pubkeys like #187 proposes. Moving
the features bitmap at the beginning of the signed payload allows
this type of change in the future. Nodes verify the integrity of the
message and then check whether there are any even bits they don't
implement. These even bits being required features would then result
in the message being discarded.
In addition to what we discussed during the call I also went ahead and
did the same reordering on `node_announcement`, which I think has the
same issue.
There is a subtle change in semantics, i.e., previously we would
add channels with unknown bits to our local view, but then ignore them …
=> BOLT7: Reorder feature bitmaps in order to allow future changes

11-payment-encoding.md
=> BOLT 11: fix formatting typo, `r` length value, and `channel_id`->`short_channel_id`

.aspell.en.pws, 04-onion-routing.md
We reuse the numeric values that we previously assigned to message
types in the failure_code, but there is no possibility for a mixup
since the latter is not transmitted directly on the transport layer
but wrapped in a return packet. Hence there is no way of confusing the
two. Added a short clarification.
Reported-by: Janus Troelsen @ysangkok
Signed-off-by: Christian Decker <decker.christian@gmail.com>
=> BOLT4: clarify that failure_code may reuse message type numbers

.aspell.en.pws, 07-routing-gossip.md
This is a recommendation to fuzz the CLTV on the HTLCs such that nodes
along the route have a harder time identifying the intended
recipient. We can either add a random offset or we can start a random
walk from the intended recipient and create a shadow route extension.
Closes #185
=> BOLT7: Add shadow route extension in the recommendations

07-routing-gossip.md
The old wording was the wrong way around - implying one would charge millions of satoshis per transferred satoshi.
=> Reword proportional fee explanation.

02-peer-protocol.md, 03-transactions.md
This is the rebase and rollup of the changes in #199 and #201 which got horribly inter-twined.
1. Change descriptions of closing tx construction to references to BOLT 3. 
2. Recipient *should* check the fee offer has improved in closing_signed.
3. Therefore, sender *must* improve closing offer.
4. Offers do not persist across reconnection, so no state req'd, and
also helps if fee has changed.
5. You don't need to re-send `shutdown` if you received `closing_signed`
(implicit acknowledgement).
6. You don't have to accept a `channel_reestablish` which requests the last
revoke_and_ack be retransmitted if you've already received `closing_signed`
(which is an implicit acknowledgement).
=> Closing tx rebase

00-introduction.md, 02-peer-protocol.md, 07-routing-gossip.md
This commit adds a 32-byte `chain_hash` value to both the
`channel_update` and `channel_announcement` messages. The rationale for
this change is that this value is already present within the
`open_channel` for identifying _which_ chain to open the channel
within. As is now, if a pair of peers had channels open on two chains
which somehow are encoded using the same `short_channel_id`, then the
announcements would be ambitious. We resolve this by explicitly
including the `chain_hash` is all channel related announcement
messages.
Note that with this change, we now require 40-bytes to uniquely
identify a channel globally.
Additionally, this modification of the channel announcement messages
allows peers to start building up a heterogenous network graph.
=> BOLT 7: add chain_hash to channel_update and channel_announcement

.aspell.en.pws, 10-dns-bootstrap.md
Thought I should finally write this up, and see if it people like it. The DNS seeds give us an easy way to bootstrap new nodes, encourage random connections and help nodes find previous peers again, should they get disconnected or change network.
This PR is still a bit thin on the policies side, but it has pointers to the Bitcoin DNS seed policy :wink: 
Also querying on features and realm could be interesting to add.
The risk in relying on the DNS seeds should be minimal. The queries get cached by the ISP, i.e., we do not see the client's IP or even how many in the ISP's network, and the authenticated encryption on the transport layer should prevent MitM attacks.
I'll polish my reference implementation a bit and link to it later.
=> bolt10: Initial draft of the subdomain structure.

04-onion-routing.md
This commit increases the max size of the encapsulated onion error
messages. This is a follow up change to the recent change that added a
`chain_hash` field to the `channel_update` message. With the addition of
this field, the largest payload encoded within the onion errors has
expanded to 138 bytes:
* msat_amount || 2_byte_len || channel_update.
As a result, the old fixed limit (including padding) is now
insufficient. We use 256 bytes here in order to give us room for future
message expansions.
=> BOLT 04: increase max size of onion payload messages

tools/spellcheck.sh
Rusty pushed a trivial "update 00-Index" patch direct to master.  Rusty broke spellcheck.  Bad Rusty, bad.
=> Spelling: expand wildcard to cover all []() patterns.

11-payment-encoding.md
The current requirement says that "A writer MUST encode the the payment request in Bech32 as specified in BIP-0173. A reader MUST parse the address as Bech32 as specified in BIP-0173, and MUST fail if the checksum is incorrect.", but according to BIP-0173, strings are not allowed to be more than 90 characters long, which in the invoice case will happen.
This PR specifies this exception, to warn that existing bech32 encoding software might be incompatible.
=> Bolt11: specify that bech32 encoding should allow addresses > 90 chars

.aspell.en.pws, 00-introduction.md
This was changed in #237 so fix it here as well.
=> BOLT00: Fix the chain_hash description

02-peer-protocol.md
That's what all implementations do, but the specification is ambiguous and currently only refers to `update_fulfill_htlc` messages.
Stumbled upon that while discussing https://github.com/cdecker/lightning-integration/issues/2.
=> BOLT 2: Clarify that only cross-signed htlcs can be fulfilled/failed

05-onchain.md
We talked about this below in the Rationale:
The fulfillment of an on-chain HTLC delivers the `payment_preimage`
required to fulfill the incoming HTLC...
Otherwise, it needs to send the `update_fail_htlc` (presumably with
reason `permanent_channel_failure`) as detailed in [BOLT
02](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#forwarding-htlcs).
But we didn't actually *say* you MUST fail incoming HTLCs after reasonable
depth!
=> BOLT 5: require to fail incoming HTLCs if HTLCs time out on chain.

.aspell.en.pws, 04-onion-routing.md
Locktime, not timelock.  Found this in my code, too, so pretty sure
it's my fault!
=> Typo fix: CTLV -> CLTV.

11-payment-encoding.md
From given specifications, it seems that signatures and checksum should match what's in the given string, and it does for one of the test vectors.
This pull request fixes other test vectors.
=> BOLT 11: Fix signatures and checksums in test vectors for payment encodings

.aspell.en.pws, 00-introduction.md, 01-messaging.md
These are minor edits for BOLT-1, constrained to punctuation and minor word changes. In a few places clauses were rearranged. The changes were grammatical or for clarity.
=> BOLT-1: Minor line edits

02-peer-protocol.md
It *is* 2R+G+S, which is 7, not six.  It's also identical to the previous one,
so just say that.
Reported-by: Shannon Appelcline <shannona@skotos.net>
=> BOLT 2: fix terminal node ctlv_expiry calc.

09-features.md
Somehow these got lost in merging; pre-approved at meeting 2017-11-27.
Reported-by: Pierre-Marie Padiou
=> BOLT 9: Adding missing option bits for option-dataloss-protect.

01-messaging.md
Noticed when @shannona cleaned up this part of the spec.
(I had named the first option `option209` but that was too ugly to live.
Nonetheless, this wording lived on.)
=> BOLT 1: options are no longer numbered.

.aspell.en.pws, 05-onchain.md
The proof-readers rightly noted how confusing the current treatment of
HTLCs is.  There are four different cases, but I tried to address them
in two separate sections, with conditionals.
This expands it out, separating sections for Our Commitment Tx and
Their Commitment Tx, then subsections for our HTLCs and their HTLCs
in each one.
It means some duplicated requirements and rationales, but it should now
be very clear.
As a side effect, we no longer refer to A and B at all: it's all US and THEM.
This needs further clearing up, but for now makes it clear what *we* need to do
for all cases.
=> BOLT 5: spell out each HTLC case (as a basis for more proofing)

08-transport.md
More clarity and copyediting. I also removed quite a few `s that didn't seem to match general usage for "code".
=> BOLT-8 Edits

05-onchain.md
See #288 and #286 for the confusion these clauses caused.
HTLC outputs can be resolved by:
1. using revocation key,
2. timeout/preimage use if that's possible, OR
3. the cheating party's HTLC-success/HTLC-timeout tx (which we already specify that you have to spend using revocation key).
Hopefully this is now clearer.
=> BOLT 5: fix reversed penalty HTLC handling clauses, make it clearer.

03-transactions.md
In this commit, we modify the cooperative closing transaction to use
version 2. Currently eclair and lnd already use version 2, while
c-lightning uses version 1. The commitment transaction already uses
version 2, so making this additional transaction (which spends the
funding output) also use version 2 would be consistent. Additionally,
as a best practice, we should be using the highest currently
defined/use transaction version.
=> BOLT3: the closing transaction now uses version 2

11-payment-encoding.md
Doesn't take any more space (we could actually reduce millionths to 24 bits,
but that starts to look silly), but it's simpler and allows for cases where
there's no payment amount.
Closes: #296
=> BOLT 11: change route to base + millionths.

02-peer-protocol.md
Usually the counterparty would only hurt itself if it chooses too low a `dust_limit`, but in the specific scenario of a data loss, we want the counterparty's commitment tx to be relayed and confirmed on the network so we better check it has a sane value.
=> Add a check on counterparty's `dust_limit` value in `open`/`accept`

01-messaging.md
Nitpick, but char 127 is `DEL`, not sure we want to print it.
=> Do not print `DEL` character

07-routing-gossip.md
This is a common term to search for, rather than onion address (which is what Tor hidden services use).
COPY-EDIT: a.k.a. or AKA or aka?  We seem to use various....
See: #309 @amkg
=> BOLT 7: mention Tor hidden service.

07-routing-gossip.md
This is a consequence of commit d1fbfd30f8ad1463e4583466f0ff12fc4b582483: we now only use *outgoing* `channel_update` messages to build a route.
Basically the node publishing the `channel_update` says: I can only send htlcs > `htlc_minimum_msat` through this channel.
I think this is consistent with the current definition of the `amount_below_minimum` error (BOLT 4):
> If the HTLC does not reach the current minimum amount, we tell them the amount of the incoming HTLC and the current channel setting for the outgoing channel:
=> Use remote's `htlc_minimum_msat` in `channel_update`

05-onchain.md
Closes: #314
Reported-by: nayuta-ueno (@ueno)
=> BOLT 5: fix annotation for to-local weight (no change in result).

07-routing-gossip.md
=> BOLT 7: there's no htlc_expiry, it's called cltv_expiry.

11-payment-encoding.md
More line editing and clarifications, also includes typo-fix from @dimitris-t in #306 and table of contents from @bcongdon in #310.
=> BOLT-11 Edits

11-payment-encoding.md
Remove duplicated word ("the").
=> Typo: Remove duplicated word ("the")

01-messaging.md, 02-peer-protocol.md
* Add missing closing parenthesis
* Use Markdown numbered list syntax (`1.` instead of `1)`)
=> Add missing closing parenthesis. Use Markdown numbered list syntax.

.aspell.en.pws, 02-peer-protocol.md
We don't actually say that!
Closes: #336
Reported-by: Matt Corallo
=> BOLT 2: clarify that feerate is in *satoshi* per ksipa.

03-transactions.md
Reported-by: Matt Corallo @TheBlueMatt
=> BOLT 3: note that key derivation test vectors apply to HTLC keys too.

07-routing-gossip.md
As agreed at the previous meeting, we use the timestamp to prune,
so it does have to be a valid timestamp.  We also suggest ignoring
if it's in the far future, too.
The minutes suggest we can prune for any reason, and that's really
true anyway; the requirements to keep it around are only SHOULD.
Closes: #302
=> BOLT 7: timestamp must be a UNIX timestamp.

01-messaging.md, 02-peer-protocol.md, 04-onion-routing.md, 05-onchain.md, 10-dns-bootstrap.md, README.md
Most links are relative to the repo, but a few were absolute. This makes them all relative, and also makes them consistently follow the `BOLT #_` format
=> Make links to BOLTs relative

.aspell.en.pws, 11-payment-encoding.md
@junderw points out how unpleasantly retro the ASCII suggestion is. The discussion also revealed the problem of the `h` field; we need to spell that out more clearly.
Closes: #319 (partial)
=> Bolt11 description field requirements, clarifications

02-peer-protocol.md
Clarify that nodes MAY initiate/handle a mutual close before the funding transaction has reached `min_depth`.
If it doesn't support it, the receiving node will just ignore the `shutdown`. Alternative was to fail the channel, which could also make sense. A feature bit was probably overkill.
I may have been a little bit verbose, let me know what you think.
This fixes #335.
=> BOLT 2: clarify that nodes may support early mutual close

01-messaging.md, 08-transport.md, 11-payment-encoding.md
Minor `proselint` edits:
* Standardization. Use "based on" instead of "based off of".
* Standardization. Use "extendable" instead of "extensible".
* Redundancy. Drop redundant use of "advance" in "advance warning".
* Redundancy. Drop redundant use of "very".
=> Minor proselint edits

.copy-edit-stylesheet-checklist.md, 02-peer-protocol.md
Fixed `markdownlint` warnings:
```
.copy-edit-stylesheet-checklist.md: 49: MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 0]
.copy-edit-stylesheet-checklist.md: 1: MD041/first-line-h1 First line in file should be a top level header [Context: "Basic checklist/stylesheet use..."]
02-peer-protocol.md: 161: MD018/no-missing-space-atx No space after hash on atx style header [Context: "#7](07-routing-gossip.md#bolt-..."]
```
=> Fix markdownlint warnings

08-transport.md
Use consistent capitalization for "MITM".
=> Use consistent capitalization for MITM

03-transactions.md
We specify this for the commitment tx, but not for the closing tx.
Reported-by: Christian Decker
=> BOLT 3: closing tx must also round outputs down to whole satoshis.

08-transport.md
* Distinguish between static and ephemeral public keys
* Use consistent method for referencing RFC:s
=> Distinguish between static and ephemeral public keys. Reference cleanup.

.aspell.en.pws, 07-routing-gossip.md, 11-payment-encoding.md
This PR adds basic security recommendations for handling of node aliases and payment descriptions. Both fields are permitted to contain arbitrary user input, making them particularly susceptible to exploits via injection attacks if the input is controlled by an adversary. These commits make inline notes of the potential for these attacks if they are not properly mitigated and provide inline references for best practices in preventing various types of injection attacks.
If anyone has more resources to include or other relevant attacks that were missed, I would welcome more suggestions :)
=> Note Possible Injection Vulnerabilities and Prevention Techniques

02-peer-protocol.md
I got an unexpected update_fee message after `shutdown` exchange,
which is currently legal:
A: shutdown (no htlcs)
B: receive shutdown
B: reply with shutdown & closing_signed
A: send update_fee & commitment_signed
A: receive shutdown
Simplest to ban any updates (currently, just update_fee) from adding a
new commitment tx while we're at the end of shutdown.
=> BOLT #2: bad update_fee after shutdown when all HTLCs cleared.

.aspell.en.pws, 02-peer-protocol.md, 03-transactions.md, 05-onchain.md
Make it clear what kind of key we're talking about.  We use the abbreviation
pubkey for public key (as it's quite common to use in field names), but
generally spell out 'private'.
(I generally prefer 'secret' to 'private' but we use private far more often
already, and we use 'secret' for things which don't directly derive keys).
Fixes: #368
=> BOLT 2,3,5: always refer to shared/pubkey/private key.

08-transport.md
Change from "Encrypting Messages"/"Decrypting Messages" to "Encrypting and Sending Messages"/"Reading and Decrypting Messages".
In order to reflect what is actually documented.
=> BOLT 8: Change from "Encrypting Messages"/"Decrypting Messages" to "Encrypting and Sending Messages"/"Reading and Decrypting Messages"

03-transactions.md, 05-onchain.md, 07-routing-gossip.md
=> Use a vs an consistently

.aspell.en.pws, 04-onion-routing.md
As was noted in by @cfromknecht [on the mailing list](https://lists.linuxfoundation.org/pipermail/lightning-dev/2018-February/000981.html), the current spec suggests a quadratic time algorithm for onion packet construction, while a linear time one is possible.
I have reworded the relevant section to introduce the concept of an ephemeral private key, which I find easier to reason about and suggests the linear time algorithm.
As a separate change that may be worth putting in a separate pull request instead, the instructions for deriving the shared secret is incomplete in that it only says to perform ECDH, but not to take the SHA256 hash of the serialized point. All implementations do this, as does the reference code in the spec. Also, the blinding factor calculation instructions had a …
=> BOLT 4: Clarify the onion construction and suggest optimization.

02-peer-protocol.md, 05-onchain.md, 09-features.md
Clarify that field `channel_reestablish`.`your_last_per_commitment_secret`
should be set to an all-zero array when no `per_commitment_secret` has
been received yet.
=> BOLT 2: Define initial value for data-loss fields

03-transactions.md
- Move the definition of the P2WSH acronym to when it is first used
- Un-bullett the funding transaction output definition
=> Define P2WSH earlier

11-payment-encoding.md
The routing tagged field of one test vector was extracted from the invoice incorrectly. The route included in the invoice has as base fee of 1 resp. 2 msat (as described in the explanation), but the extracted bech32 part had a 0 msat base fee.
Btw: I found this when implementing a [test for rust-lightning-invoice](https://github.com/rust-bitcoin/rust-lightning-invoice/blob/master/src/parsers.rs#L474)
=> BOLT 11: fix test vector routing part

02-peer-protocol.md
~~This requirement is subtle: firstly, we ensure that both reserve values are above
both dust limits.  But we also need to make sure that fees (which can eat into
reserves) always leave enough left: it makes sense to ensure that worst-case
fees are actually covered by the channel capacity, otherwise the channel is
likely to be useless anyway.~~
I re-read the fee payment section: we can simply assert that reserves are above dust.
=> BOLT 2: ensure that we always have a non-dust output.

10-dns-bootstrap.md
I've tried to clarify the query semantics in BOLT10 by briefly exemplifying how to pass the conditions to the DNS seed server. The pull-request aims to fix #395 that I created after a brief exchange with @cdecker on the lightning-dev mailing list.
=> Clarify query semantics in BOLT10

02-peer-protocol.md
A channel may be established, but this is not mandatory. Furthermore, the connection initialization has to happen first.
=> BOLT2: Rephrase channel establishment introduction

04-onion-routing.md
We think that `mandatory` is more in line with the rest of the BOLT, but in any case the wording in the specs leaves room for interpretation (we believe it is mandatory and lnd for example believes it is optional) so it needs to be specified.
=> BOLT4: `channel_update` is mandatory in `UPDATE` error messages

00-introduction.md
Supersedes PR #384 since I couldn't push to @shannona's branch. Quoting from the original PR:
>This is a big change to the glossary in BOLT-0.
>
> The overarcing changes are:
>
> 1.) Reorganized glossary to be alphabetical
> 2.) Add copious "See also:" lines to cross-reference containers, contents, and other related entries.
> 
> Changed Definitions: Peer and node were revised based in on discussions with Rusty; commitment revocation secret key was changed to be commitment revocation private key based on #377.
>
> New Definitions: New words added based on their usage in the bolts were: announcement, closing transaction, final node, hop, origin node, processing, node, receiving node, receiving peer, revoked commitment transaction, sending node, sending peer.
>
> (I suspect the reorg will …
=> BOLT-0 Glossary Reorg & Expansion

.aspell.en.pws, 01-messaging.md, 07-routing-gossip.md, 09-features.md, tools/extract-formats.py
Here's an early draft, please bikeshed @Roasbeef @cdecker @pm47 @sstone
=> Final: Channel range queries

11-payment-encoding.md
a.k.a. landonmutch style, where requirements are explicit and bullet-pointed.
This also tightens requirements:
1. New requirement (previously implied) that writer use correct prefix.
2. Reader MUST rather than SHOULD fail malformed `amount`.
It also makes it clear that writer can omit the multiplier.
Fixes: #442
=> BOLT 11: reword Human-Readable Part Requirements in modern form.

02-peer-protocol.md
Reported-by: Matthias Grundmann @mattias-g
Fixes: #453
=> BOLT 2: fix placement of chain_hash requirement.

10-dns-bootstrap.md
Copy edit BOLT10 to bring in line with stylesheet guidelines
=> BOLT 10 copy edit

07-routing-gossip.md
The fee calculation in BOLT 7 appears to imply that proprtional
fees must be paid on the incoming amount, not the to_forward amount
This is inconsistent with what is actually implemented in the
field (which uses amount_to_forward) and also would make
pathfinding more complicated as the fee would depend on itself,
making calculation no longer simple.
=> Correct fee calculation in BOLT 7

07-routing-gossip.md
This optional padding makes it very difficulty to deserialize
node_announcements into internal structs for storage and then
reconstruct the original node_announcement, plus are unused on the
network today and no known implementations construct
node_announcement messages with them.
=> Remove padding within node_announcement address data

01-messaging.md
It seems like a reasonable thing to do but the spec isn't currently clear on that, leading to differences between implementations.
See https://github.com/lightningnetwork/lnd/issues/1882.
=> BOLT 1: Reply to unknown channels with an error

11-payment-encoding.md
I keep forgetting what the base currency unit is in BOLT11, so make it explicit.
=> Make unit explicit encoded in BOLT11 invoice

07-routing-gossip.md
It's unclear what it means to `discard` a channel. Instead,
let's use the common phrase to `fail` a channel.
I'm assuming that `fail` is the same as `discard` here, but maybe it's meant to say discard the `message`? (But that seems unlikely, given the context).
=> gossip: clarify what it means to 'discard a channel'

02-peer-protocol.md
issue #472
In this sequence, three `commitment_signed` and `revoke_and_ack` are required.
=> BOLT2: both nodes send `update_add_htlc`

07-routing-gossip.md
make it a bit easier to read.
fixes #443
=> BOLT 7: readability fixup

07-routing-gossip.md
Technically this change may result in channels_announcements only
coming from one end. However, because c-lightning already implements
announcement_signatures in this way, in practice this will improve
reliability of channel_announcements.
[ After much bikeshedding, wording rewritten but same effect -- RR ]
Closes #468
Closes: #474
=> BOLT 7: Push the sending of announcements_signatures back a little (amended wording)

03-transactions.md
It seems remote_funding_privkey in the internal part has wrong length 34 instead of 33 (32-private key and 1 in the end).
I deleted 01 in the end and managed to obtain the correct pubkey and signature.
=> BOLT 3: fix private key in internal part

03-transactions.md
=> Specify valid signature hash flags (SIGHASH_ALL)

02-peer-protocol.md
This seems to be a cause of stuck HTLCs on the network: c-lightning has
done this for a while now (since 0.6.1).
Decided-at: Adelaide Summit 2018
=> BOLT 2: advise ping-before-commitment_signed on quiescent connections.

.aspell.en.pws, 02-peer-protocol.md
Because apparently we're dead-set on making sure that the obvious way to implement the spec is incorrect (and will lead to bugs downstream of implementors, see #475), we need to be extra-doubly-sure that we spell this out. Note that based on their wiki at least @acinq (@pm47 @sstone) have a bug here, and the lnd/c-lightning docs need to clarify this as they appear to indicate to users they can do this.
=> Clarify temporary_channel_id's acceptable usages

02-peer-protocol.md
In the description here, the target is not only `HTLC`
but also general `update`.
=> BOLT 2: `update` not `HTLC` in `Normal Operation`.

00-introduction.md, 02-peer-protocol.md, 05-onchain.md
=> BOLT 0,2,5: `closing transaction` not `(mutual) close transaction`.

03-transactions.md
Both HTLC-success/HTLC-timeout can be spent by a valid penalty
transaction
Both HTLC type of tx can be spent by a remote peer in knowledge of local per_commitment_secret. Does it is something out of date or I'm missing something ?
=> BOLT 3 : Fix ambiguity on HTLC transactions spendable by a penalty one

02-peer-protocol.md
And added an equivalent requirement for `next_local_commitment_number`.
=> fix a requirement mistake of `next_remote_revocation_number`.

04-onion-routing.md
For some relaying errors it makes more sense to report the values of the outgoing HTLC rather than the incoming HTLC.
=> BOLT 4: Report outgoing HTLC values when appropriate

02-peer-protocol.md, 03-transactions.md
We express it has how the outputs are ordered, but the only way you can
detect that is by the htlc_signatures order, which is the part which really
matters.
I finally reproduced this, BTW, which is why I'm digging it up!
Closes: #448
=> BOLT #2: order htlc_signatures by BIP69 + increasing CLTV.

04-onion-routing.md
914ebab9080ccccb0ff176cb16b7a6ba21e23bbe effectively deprecated this, but
left it for "reject if more than 2x expected amount" case.
Leaving it for gross overpayment still leaves an attack on the current
network in practice (all implementations I know of reject grossly excessive
payments), and removing it causes our code to nicely break when regenerating,
since that error code is now not defined anywhere.
[ @TheBlueMatt I invited you to the repo, so I can request reviews from you in future ]
=> BOLT 4: remove incorrect_payment_amount altogether.

03-transactions.md
=> Specify OP_DATA to express accepted/offered_htlc_script with same

02-peer-protocol.md
We wonder on rust-lightning if it was receiving or sending node policy for max_accepted_htlcs/max_htlc_value_in_flight_msat which was referenced by pronoun "its". Found it confusing for a non-native, if you've a better wording go ahead.
=> Clarify ownership of max_htlc limits at receiving update_add_htlc

02-peer-protocol.md
Uses more specific and consistent language ("the"/"that" instead of "an" where possible). Also helps avoid confusion with unrelated HTLCs that serve other payments but are shared by the same two nodes.
=> Rephrase Forwarding HTLCs Requirements

02-peer-protocol.md
Saying "the risk is only to the node *accepting* the HTLC" is confusing
because merely accepting an HTLC is risk-free.  The risk comes from
accepting *responsibility to route the payment*, i.e. offering an HTLC
of your own in the next channel on the path, where a too-small
difference in the HTLC values could end up with you cheated out of a
payment.
This revised paragraph hopefully makes that clearer.
(My thanks to @jnewbery and @cdecker for helping me understand what was going on here.)
=> BOLT2: rephrase cltv_expiry_delta text about accepting HTLCs

08-transport.md
When the notation of the noise protocol framework is being introduced the terms `ck` and `k` are being explained but `e` and `s` are only referred to was public keys. I fixed that by stating what they stand for and noting that `s` is usually the the `nodeid` in the context of the Lightning Network protocol.
=> [BOLT 08] added elaboration of Noise Protocol terms when used first

05-onchain.md
The two paragraph seem quite redundant and repetitive. Perhaps the resulting one can even be simplified even further.
=> BOLT5: Unify two practically redundant paragraphs

02-peer-protocol.md
This seems a typo. It seems it should say channel rather than connection.
If not, why fail the connection (presumably to reconnect later? or to ban the node?) instead of failing the channel?
Or are they just equivalent?
=> BOLT2: past fulfillment deadline fails channel

.aspell.en.pws, 01-messaging.md
~~This proposal outlines a TLV format intended for wire messages. It contains additional considerations for gossip messages that would require maintaining the ability to verify signatures over unknown fields, and the ability to propagate those messages to peers.~~
~~This proposal makes different tradeoffs from #603 in terms of:~~
- ~~requiring strict canonical encoding~~
- ~~fixed-size length encoding~~
- ~~supporting reserialization of unknown records~~
- ~~using 255 as the sentinel type identifier~~
- ~~removing even/odd requirement from the parsing logic, favoring negotiation via feature bits or application of such constraints external to the fundamental parsing requirements~~
After significant feedback and discussion, the proposal now entails:
- `type` and `length` both use the …
=> BOLT01: TLV proposal

.travis.yml, 01-messaging.md, 02-peer-protocol.md, 04-onion-routing.md, 07-routing-gossip.md, tools/extract-formats.py
This rewrites tools/extract-formats.py to handle TLVs and subtypes (@niftynei did that, I just refactored as that built on my prior code which was awful).  The new format is still simple CSV, but much more regular.
But it also replaces raw lengths with types in the spec.  I think this makes it much clearer, as well as making building on top more accessible.
=> BOLT 1: Spec field formatting and parsing

11-payment-encoding.md
Isn't it BOLT 4 that specifies the max overpayment amount instead of BOLT 5?
BOLT 4 states: "if the amount paid is more than twice the amount expected [the final node] SHOULD fail the HTLC."
=> BOLT 11: fix link

03-transactions.md
`OP_CHECKLOCKTIMEVERIFY` and `OP_CSV` use an inconsistent naming convention in the document, since `OP_CLTV`/`OP_CLV` is not used but `OP_CSV` is used. Update OP_CSV to match the `OP_CHECKLOCKTIMEVERIFY` convention by using `OP_CHECKSEQUENCEVERIFY` instead
=> Change opcode reference format

.aspell.en.pws, 07-routing-gossip.md
While going through BOLT #7 I was confused by this receiving node requirement for `channel_update` message: "if the `timestamp` is equal to the last-received `channel_update` AND the fields (other than `signature`) differ: MAY blacklist this `node_id`; MAY forget all channels associated with it." On the outset it might read to "`timestamp` should be same, the `signature` should be same as previous but if the other data is different; then blacklist the `node_id`". However, if `signature` is same as previous update but data is different, then the `signature` would be rendered invalid. And since `signature` check is done prior to the `timestamp` check, this situation of checking may not arise. So this check seems to be redundant. However, Mark H corrected me on stackexchange …
=> BOLT #7: receiving node requirements related to timestamp for channel_update message

07-routing-gossip.md
Small typo, broken off from #647
=> BOLT07: correct gossip_timestamp_range to gossip_timstamp_filter

09-features.md
I know this is kind of stupid, but it makes it easier to read in plain text.
I totally understand if people don't think it's worth it.
It doesn't affect how github displays the file, the markdown is still correct.
=> BOLT9: Format table

.aspell.en.pws, 01-messaging.md, tools/spellcheck.sh
This commit modifies the varint encoding used for TLV types and lengths
to use a custom format called BigSize. The format is identical to
bitcoin's CompactSize, except it replaces the use of little-endian
encodings for multi-byte values with big-endian. This is done to prevent
mixing endianness within the protocol, since otherwise CompactSize would
be the first introduction of little-endian encodings.
=> BOLT01: swap CompactSize for BigSize in TLV format

04-onion-routing.md
Mention that `outgoing_cltv_value` has to be equal to `min_final_cltv_expiry` and `amt_to_forward` has to be equal to `amount`, as seen in the invoice
=> Rephrase last node payload requirements

02-peer-protocol.md
(No spec change, just wording)
The "local" and "remote" here are just *confusing*.  Each side says
where it's at, and the other side retransmits based on that.
We could call it 'number_of_next_commitment_i_expect_to_receive' and
'number_of_next_revocation_i_expect_to_receive' but that's getting
silly.
These names were a major source of confusion while writing tests!
=> BOLT 2: remove local/remote from reestablish field names.

07-routing-gossip.md
`announcement_signatures`
Fail channel if `short_channel_id` not correct.
=> BOLT7: (announcement_signatures) Fail channel if `short_channel_id` not correct.

07-routing-gossip.md
Related to pull [#621 ](https://github.com/lightningnetwork/lightning-rfc/pull/621#discussion_r304777931)
Corrected the indentation in the otherwise section in the `timestamp` check of the `channel_update` message. Both the actions that needed to be taken appeared at the same level which had to be indented.
=> BOLT #7: Correct indentation typo in channel_update message

04-onion-routing.md, 09-features.md
* Removed mentions of the deprecated `hops_data` field
* Formatting
Nothing fancy to see here ;)
=> Bolt 04: fix a few left-over spelling / clean-up nits

tools/extract-formats.py
The first two are in #631 already, but the third one is new: @ZmnSCPxj points out in #643 that describing TLVs using ordered lists causes them to be merged on formatting, so we should use unordered lists (which is also logically consistent).
=> Simple tooling fixes

02-peer-protocol.md
Make it more obvious what the expected value of `my_current_per_commitment_point` is.
=> option_data_loss_protect: concretely define `my_current_per_commitment_point`

04-onion-routing.md
In commit 914ebab9080ccccb0ff176cb16b7a6ba21e23bbe the incorrect_payment_amount error was merged into incorrect_or_unknown_payment_details to prevent a probing attack that allowed intermediate nodes to learn the final destination of a payment.
A similar attack is possible using the htlc expiry value. By trying payments with the correct amount but low expiry values to candidate destinations, an incorrect_or_unknown_payment_details error can be
elicited. This would signal that the probe payment was sent to the final destination.
For the intermediate node to determine the correct amount, an estimate must be calculated. A logical choice would be the outgoing amount of the intermediate node plus some allowance for routing fees that would otherwise be paid to subsequent nodes along the path. …
=> BOLT 4: Merge final_expiry_too_soon into incorrect_or_unknown_payment

02-peer-protocol.md, 03-transactions.md
Added descriptions of how a 2-of-2 multisignature verification is used for enforcing timelocks when timing out on-chain offered HTLCs as well as spending on-chain received HTLCs in the success case.
I say implicitly enforced to mean that these timelocks do not show up explicitly in any of the HTLC output scripts.
It took me a lot of time and effort to reason these facts out of the existing documentation so I figured I'd propose to add it.
=> BOLT 3: Explicit description of implicitly enforced timelocks on HTLC outputs

07-routing-gossip.md
If a node sends its own `channel_update` to a peer node before receiving a `funding_lock`, the peer node may discard because it has not `short_channel_id` yet.
```
ex: node-A and node-B check blockchain every 30 seconds.
node-A                    node-B
|                         |
~~~ funding_tx is in block ~~~
|                         |
[detect new block]           |
[calc short_channel_id]      |
[create channel_update]      |
|                         |
|---funding_locked------->|
|---channel_update------->|
|                         |cannot compare short_channel_id
|                         |  ===> discard channel_update
|                         |
|                         |
|                  [detect new block]
|                  [calc short_channel_id]
|                  [create …
```
=> BOLT7: channel_update after exchange funding_locked

11-payment-encoding.md
We will want these for the payment-nonce proposal, since we'd eventually like to make that compulsory.  So I'm pushing this now so we can all deploy it ASAP.
(Note: this PR is simply extract from #643 )
=> Bolt11 feature bits

04-onion-routing.md
The specification currently doesn't specify the case where the onion per-hop
payload can't be correctly decoded.
This is somewhat fine with the fixed frames because every field of the payload
can always be interpreted as a numeric value from the input bytes, so it leads
to application errors in upper layers when those values are actually
interpreted (and we realize that for instance we have an invalid
`short_channel_id` value).
With variable-length tlv streams in the onion payloads, we will encounter
decoding errors (duplicate tlv types, invalid ordering, etc) and the spec
should define the failure code to use in that case.
=> BOLT 04: Add failure code for invalid payload.

03-transactions.md
NIT but it rendered poorly when tabs where used (too much spaced) whereas spaces were previously used.
=> BOLT #3: Indentation consistency in key derivation algorithms

.aspell.en.pws, 07-routing-gossip.md, 09-features.md, bolt07/extended-queries.json
This is a new pull requests that supersedes #519 .
It addresses issues with the original proposal, mainly that it defined a new set of messages, adding complexity to a simple gossip protocol that we knew was limited in the first place.
This proposal does not add new messages, or feature bits, and is fully compatible with existing implementations. Instead of defining new messages it extends existing ones with additional data, that will be ignored by nodes which do not implement extended queries (see [BOLT #1](01-messaging.md)).
Nodes that support extended queries will append an additional extended query flag to their `query_channel_range` queries. If the receiver supports extended queries and understands this flag, it will append the requested additional data to its `reply_channel_range` …
=> BOLT7: extend channel range queries with optional fields

07-routing-gossip.md
These fixes make our implementation compile again :)  They match what we had implemented, and what the spec actually says, too.
=> BOLT 7: gossip_query_ex typos.

02-peer-protocol.md
We might argue this does not apply if you set `minimum_depth` to 0, since
you're assuming trust (TurboChannels-style), but it needs to be specified.
See: CVE-2019-12998 / CVE-2019-12999 / CVE-2019-13000
=> BOLT 2: specify that you can't send `funding_locked` until you've checked the txout

01-messaging.md
Looks like the word 'not' is missing. As the context is bytes may as well be explicit.
=> BOLT #1 'minimally encoded' explanation needs inverting

01-messaging.md
This PR defines a type range for custom tlv records. The goal is to prevent unofficial fields from allocating identifiers in the official range. This could cause problems when new fields are added to this specification and turn out to collide with custom records that are used in the wild.
=> BOLT 4: Define custom tlv type range

02-peer-protocol.md
I don't think this sentence is necessary. Or perhaps more explanation is needed.
=> remove `funding_locked` future section

07-routing-gossip.md
Pure cosmetic, noticed while working on #678.
=> bolt07: remove trailing tabs

.aspell.en.pws, 01-messaging.md, 02-peer-protocol.md, 07-routing-gossip.md, 09-features.md, 11-payment-encoding.md
We simply specify how they're presented in the three different contexts.
Consider these theoretical future features:
`opt_dlog_chan`: a new channel type which uses a new discrete log HTLC
type, but can't support traditional HTLC:
* `init`: presents as odd (optional) or even (if traditional channels
not supported)
* `node_announcement`: the same as above, so you can seek suitable peers.
* `channel_announcement`: presents as even (compulsory), since users need
to use the new HTLCs.
`opt_wumbochan`: a node which allows channels > 2^24 satoshis:
* `init`: presents as odd (optional), or maybe even (if you only want
giant channels)
* `node_announcement`: the same as above, so you can seek suitable peers.
* `channel_announcement`: not present, since size of channel indicates
capacity. …
=> Flat features: far simpler solution for feature bits.

04-onion-routing.md
I recently made a cut & paste bug with the protocol tests, and
paid an HTLC of amount 100M msat, but with only a 1M msat `amt_to_forward`
in the hop_data.  To my surprise, it was accepted.
This is because we allow overpaying the routing fee (considered 0
for the final hop).  This doesn't make sense for the final hop: anything
but exact equality implies a bug, or that the previous node took the
wrong amount from the payment.
=> BOLT 4: don't allow a "fee" for the final node.

04-onion-routing.md, 11-payment-encoding.md
~(Based on #643 so ignore first three commits)~
This means the BOLT11 invoice must offer it (we already say it must set the field if it offers it), and that the receiving node must require it (again, we already say it must check it if it requires it).
Without the payment_secret, MPP payments are especially vulnerable to probing attacks: unlike normal payments (with amounts) they can be detected with 1msat payment probes.
=> *Require* payment_secret for multi-part payments

07-routing-gossip.md, 09-features.md
* BOLT 4 explicitly indicates var_onion_optin may appear in a BOLT 11 invoice, however, BOLT 9 only indicates it is available in init and node_announcement contextx. Resolve this conflict in favor of BOLT 4 as there doesn't seem to be much reason to *not* allow it in BOLT 11 invoices.
*  Do not allow routing to a node with unkown feature bits set. This appears to have been an oversight in the flat features spec, and is somewhat implicitly relied on for several new feature bits - if var_onion_optin is set on a node_announcement (its not allowed on a channel_announcement), then trying to route through that node using the pre-tlv formt is somewhat nonsensical, and should be forbidden.
=> Resolve two spec oddities regarding new features.

04-onion-routing.md
#711
> For the final node, this value MUST be exactly equal to the incoming htlc amount, otherwise the HTLC should be rejected.
=> BOLT4: don't allow a "fee" for the final node(failure messages)

04-onion-routing.md
As reading of commit 6729755f shows, `final_expiry_too_soon` was
17, not PERM|17.
Note that because we folded a previously non-permanent failure into
the now-permanent PERM|15 failure code, modifications to payment
algorithms may now be needed to specificalyl detect this case,
otherwise payment algorithms may give up in some edge cases where
blocks are mined while payments are in-transit between sender and
receiver.
=> 04-onion-routing.md: Fix factual error about `final_expiry_too_soon`.

01-messaging.md, 04-onion-routing.md, 09-features.md, 11-payment-encoding.md
This PR adds an additional column to our feature table in BOLT 09, enumerating any dependencies that a feature pair has. At the moment, there are 3 such pairs that have dependencies, and more will be added in the near term. The motivation is to offer a concise way to describe these relations, and also simplify how we specify behavior gated by features with dependencies.
Consider the `basic_mpp` feature, which (as of #712) depends on `payment_secret` and transitively depends on `var_onion_optin`. Instead of specifying (or coding) `has(basic_mpp) && has(payment_secret) && has(var_onion_optin)` everywhere we need to gate `basic_mpp`, this allows us to isolate the gate to only `basic_mpp` since the transitive requirements are assumed to be already validated..
An implementation of this …
=> 09+11: require transitive feature dependencies

01-messaging.md
This PR defines a message type range for custom messages. The goal is to prevent unofficial messages from allocating types in the official range.
Experimentation and application-specific messages should have a way to choose "safe" message types that won't collude with a future spec-ed (official) message.
=> BOLT 1: Define custom message type range

11-payment-encoding.md
When the `p` multiplier is used, the amount MUST be divisible
by 10 since the resolution used internally is millisatoshi.
This addresses but does not close-   #692.
=> Specify that resolution of amount is msat

07-routing-gossip.md
As more nodes on the network use timestamp_filter to block gossip
floods, we've seen some propagation problems.  This should avoid it
(and is implemented now by c-lightning).
See: https://github.com/ElementsProject/lightning/pull/3152
=> BOLT 7: be more aggressive about sending our own gossip.

02-peer-protocol.md, 03-transactions.md, 04-onion-routing.md, 08-transport.md
ECDSA signatures in Bitcoin are DER-encoded but public keys are not.
The compressed format for public keys is for example standardized in
Sections 2.3.3 and 2.3.4 of
Standards for Efficient Cryptography, SEC 1: Elliptic Curve
Cryptography, Certicom Research, Version 2, 2009,
https://www.secg.org/sec1-v2.pdf
=> Remove reference to DER encoding for public keys in compressed format

04-onion-routing.md
Change `HMAC` to lowercase in packet description, as it later appears in
lowercase. The uppercase version is used in the `hops_data`, so this
change helps avoid confusion.
=> Keep HMAC case consistent

.aspell.en.pws, 03-transactions.md, 07-routing-gossip.md
We're using unsigned big-endian comparison.
Thanks to @real-or-random for raising this.
=> Clarify numerical comparison of pubkeys

11-payment-encoding.md
requires s
s requires payment_secret bit set
which requires 9 tag
Therefore 9 tag is also required.
=> [BOLT11] Feature Bits MUST be required

01-messaging.md, 02-peer-protocol.md
The spec already prepared a hook to add additional information to existing
messages (additional bytes at the end of a message must be ignored).
Since we're using TLV in many places, it would make sense to use that optional
additional space at the end of each message to allow an optional tlv stream.
We keep the "additional bytes must be ignored" rule for what happens after that
tlv stream, giving us extra flexibility to add another type of optional content
to existing messages later if needed.
This was already proposed in #630 but rejected. I found additional reasons to
specify this now rather than on a per-message basis. We don't want to have two
competing and incompatible ways of extending existing messages.
Imagine node A and node B are peers, both running experiments by leveraging the …
=> Bolt 1: Specify that extensions to existing messages must use TLV

.aspell.en.pws, 11-payment-encoding.md
This addresses #692. But as part of #692 some have also requested that the RFC is changed to specify that any amount with the pico-multiplier MUST be divisible by 10. This request is addressed in PR #700  (now merged).
+
+Breakdown:
+
+* `lnbc`: prefix, Lightning on bitcoin mainnet
+* `9678785340p`: amount (9678785340 pico-bitcoin = 967878534 milli satoshi)
+* `1`: Bech32 separator
+* `pwmna7l`: timestamp (1572468703)
+* `p`: payment hash...
+* `d`: short description
+  * `8d`: `data_length` (`8` = 7, `d` = 13; 7 * 32 + 13 == 237)
+  * `gfkx7cmtwd68yetpd5s9xar0wfjn5gpc8qhrsdfq24f5ggrxdaezqsnvda3kkum5wfjkzmfqf3jkgem9wgsyuctwdus9xgrcyqcjcgpzgfskx6eqf9hzqnteypzxz7fzypfhg6trddjhygrcyqezcgpzfysywmm5ypxxjemgw3hxjmn8yptk7untd9hxwg3q2d6xjcmtv4ezq7pqxgsxzmnyyqcjqmt0wfjjq6t5v4khx`: 'Blockstream …
=> Add bolt11 test vector with amount in `p` units

04-onion-routing.md
A missing parenthesis closure and some spurious trailing tabs (in text sections, did not touch Go code nor test vectors indentation).
=> bolt-04: fix some typos

07-routing-gossip.md
Its not uncommon to be multi-homed with different addresses, so we should probably allow nodes to do this. Also, it seems like this is pretty much universally not actually enforced on the network.
=> Allow More than one Address of a given type

07-routing-gossip.md
First a trivial renaming of the confusing `complete` field.
Then, we insist that query_channel_range replies be in order (everyone now does this anyway) and non-overlapping (ditto: c-lightning had strict enforcement on this, which was overzealous but means everyone now does it that way).  Currently c-lightning maintains a bitmap for every block it requested, but it's much simpler to assume ordered replies, and simply check if we received the final one.
=> Reply channel range simplification

.aspell.en.pws, 03-transactions.md
I guess everyone get it right for its onchain transactions but I found some of my test transactions failing against core so make it explicit spending transaction must conform to MINIMALIF. Currently, it's only a standard rule, not a consensus one. Not conforming transaction will be rejected by core, which can be quite annoying for the timeout case.
If you have a better way to encode this, I will modify.
More context:
https://github.com/bitcoin/bitcoin/pull/8526
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2016-August/013014.html
=> Make it explicit witness must conform to MINIMALIF

02-peer-protocol.md
Add an additional "reserve" for funders on top of the real reserve to
avoid getting in a state where the channel is unusable because
of the increased commit tx cost of a new HTLC.
Requirements are only added for the funder sending an HTLC.
Fundee receiving HTLCs may choose to verify that funders apply
this, but it may lead to an unusable UX.
@halseth do you want to chime in since you've been confronted
with this issue on the lnd side?
Fixes #728. (see the issue for a longer discussion)
=> Avoid stuck channels after fee increase with additional reserve

09-features.md
Turns out Eclair doesn't, and as c-lightning 0.8.2 implemented and Matt noticed in https://github.com/lightningnetwork/lightning-rfc/pull/770, it should have been ODD anyway!
See also: https://github.com/ElementsProject/lightning/issues/3703
Closes: #770
=> BOLT 9: don't advertize option_support_large_channel in channel_announcement

07-routing-gossip.md
- The current text refers to 'three gossip messages' for channel discovery. In fact, there are three gossip messages for node discovery _and_ channel discovery.
- The introductory paragraph describes node discovery and channel discovery, but changes the ordering. Keep the same ordering throughout the paragraph for readability.
=> Clarify Bolt 7 intro

.aspell.en.pws, 01-messaging.md, 04-onion-routing.md, 07-routing-gossip.md
1. It's `bigsize` not `varint`: having both is confusing; we chose the name bigsize, so use it explicitly.
2. I accidentally used `u8` (a c-lightning internal alias) instead of byte in BOLT 7.
3. Put `bigsize` in our Fundamental Types section.
=> Complete the Fundamental Types.

03-transactions.md
It turns out everyone does `P[B / 8] ^= (1 << (P % 8))`, which is not what the spec says to do (it implies you would treat P as a bitstring numbered 255 to 0).
See this stackoverflow question:
https://stackoverflow.com/questions/49928131/lightning-secret-generation-from-seed
Reported-by: Janus Troelsen @ysangkok (on Twitter)
=> BOLT 3: fix definition of flip(B) in P.

01-messaging.md
Closes #776 as discussed within the issue
=> Clarification on the occurences of TLV records with the same type

08-transport.md
Presumably, this `decryptWithAD` also has a MAC check that can potentially fail, like the other ones. Unlike the other ones, this one does not describe what MUST happen if the MAC check fails.
Maybe it's just a nitpick. Terminating the connection without any further messages seems sensible to me in this case, but I'm not 100% sure if it's necessary, or even if it could be harmful. So don't take my word for it that this is the right behavior: think about it.
=> BOLT 8: add missing MAC check in Act Three

04-onion-routing.md, 08-transport.md
7539 is obsoleted by [8439](https://tools.ietf.org/html/rfc8439), as [mentioned in 7539](https://tools.ietf.org/html/rfc7539).
=> Replace RFC7539 with RFC8439

11-payment-encoding.md
Explicitly mirror the BIP-173 advice for QR codes, and note the reader
requirements.  In addition, we change the case of one of the examples
to ensure testing.
Fixes: #659
Alternative-to: #661
=> BOLT 11: make UPPERCASE explicit.

02-peer-protocol.md, 11-payment-encoding.md
Many channels use a value below 6, which is really insecure (there are more than 2k such channels on mainnet).
While less risky, there are more than 7k channels with a value below 12.
This indicates that the spec should probably make the risks a bit more clear to help guide node operators.
=> More conservative `cltv_expiry_delta` recommendations

07-routing-gossip.md
This PR modifies the recommended pruning requirements to use the latest
`channel_update`'s timestamp rather than the oldest. The rationale is that
using the oldest timestamp inadvertently retrains channels for which only
one side of the channel continues to send fresh `channel_update`s.
Consider a new node that makes a channel to y'alls, but then disappears.
The current pruning strategy will keep the channel in its routing table
because y'alls continues to send fresh `channel_update`s, but the channel
is actually unusable because the other party is never online. The new strategy
will remove these low-success nodes/channels from the routing table and
only keep channels where both endpoints have indicated recent activity.
This reduces the number of channels in the public graph by 25% at the …
=> BOLT07: prune if oldest channel_update is > 2 weeks old

02-peer-protocol.md
See CVE-2020-26895 for context.
Note, the requirement is on every remote signature reception instead of a global note. We make this a reception requirement, which doesn't prevent implementation to harden by normalizing to low-S at transactions broadcasting.
=> Fail channel in case of high-S remote signature reception

01-messaging.md, 02-peer-protocol.md, 04-onion-routing.md, 07-routing-gossip.md, tools/extract-formats.py
It might seem a bit redundant, but for me it would have helped to have this link.
I assumed that the payload has the format of `tlv_stream`. Technically, this leads to a small inconsistency though: BOLT 4 says somewhere that "no TLV value can ever be shorter than 2 bytes", but `tlv_stream` can technically consist of zero `tlv_record` elements, resulting in zero bytes. I don't know if it is ever possible for a node to know what to do when it receives a zero-byte payload. It'd have to be some kind of (supposedly useful and well-defined) "default behavior" of the node.
Closes #800
=> BOLT 4: link to BOLT 1 for tlv_payload format

05-onchain.md
See CVE-2020-26896 for context.
=> Prevent preimage reveal collision while claiming onchain incoming HTLC

02-peer-protocol.md
The existing requirements were not specifying the case where both a `commitment_signed` and `revoke_and_ack` need to be retransmitted.
This is an important case to specify because if the relative order is not preserved, the channel will close.
See for example the following two scenarios.
```
A            B
<---add-----
----add---->
<---sig-----
----rev----x
----sig----x
```
A needs to retransmit:
```
----add-->
----rev-->
----sig-->
```
With some leeway on when she sends the `add`: it can be either before or after `rev`, she can choose to not send it at all, or update the fees. The important point is that `sig` must occur **after** `rev`.
```
A            B
<---add-----
----add---->
----sig----x
<---sig-----
----rev----x
```
A needs to retransmit:
```
----add-->
----sig-->
----rev-->
``` …
=> Clarify relative order of some messages after reestablish

05-onchain.md
If `option_anchor_outputs` applies, the cheating node can pin spends of its
HTLC-timeout/HTLC-success outputs thanks to SIGHASH_SINGLE malleability.
Using a single penalty transaction for all revoked outputs is thus unsafe as it
could be blocked to propagate long enough for the `_local node's main output_ 's
relative timelock to expire and the cheating party escaping the penalty on this
output.
I think we may just make this an unconditional requirement, indifferently of anchors.
=> Require to claim revoked local output in its own penalty tx post-anchor

03-transactions.md
I noticed a few inconsistencies in the weight constants. 
I guess implementations just use the hardcoded constants for `HTLC-timeout` and `HTLC-success` when doing tx constructions (this is what lnd does), so I added a note here that we should continue using this value even though it is off by one.
=> Correct htlc witness size calculations

07-routing-gossip.md
We previously insisted that `reply_channel_range` messages were not overlapping: blocks content could not be split across multiple messages.
This made it possible to implicitly figure out when sync was complete, so we re-purposed the previous `complete` field to a `full_information` field.
We now revert that change to allow blocks to be split across multiple messages. An explicit flag is thus needed to signal that sync is complete. AFAIK, no-one actually reads the `full_information` field and use its info: so it's ok to re-purpose it.
Implementations should probably deploy this in multiple phases:
1. Write the `sync_complete` field: set it to `true` only in your last `reply_channel_range`
2. Read and interpret `sync_complete`
3. Split blocks across multiple `reply_channel_range`
A safer …
=> Gossip queries: sync complete is back

02-peer-protocol.md
Routing nodes have an incentive to use low fees when opening channels to ensure their activity is economically viable.
However, when a funding transaction takes too long to confirm, the fundee may have forgotten the channel. In that case the funder is forced to broadcast the first commit tx to get his funds back and then open a new channel, which is costly.
We can avoid this issue by having an explicit commitment to a block before which the funding tx will be confirmed. The fundee will keep the channel around for that duration, and the funder needs to ensure the funding tx confirms before that deadline (using CPFP on a change output for example). This gives clearer guarantees for both the funder and fundee.
As discussed during the spec meeting, I update this PR to a simple version where …
=> Add funding expiry to channel open

11-payment-encoding.md
Judging from the comment
https://github.com/bitcoin/bitcoin/pull/18267/files#r491150895 in the
Signet PR all test networks should have the same bech32_hrp prefix (even
regtest). That's why `tb` was chosen for Signet as well.
This is not optimal for LN as invoices shouldn't be vague in
what network they were issued for.
Therefore we add the explicit prefix `lntbs` for Signet invoices.
This PR was motivated by this comment: https://github.com/lightningnetwork/lnd/pull/5025#discussion_r575984300
The actual value (`lntbs`? `lnbcsn`? `lnsn`?) is open for discussion IMO.
For reference, CL already wrote some code to handle the current issue of testnet and signet using the same prefix: https://github.com/ElementsProject/lightning/blob/030a19a8af989db38d3c547a81faff5b1e11608d/common/bolt11.c#L613
=> Bolt 11: add distinct HRP prefix for Bitcoin signet

04-onion-routing.md
As seen in https://github.com/lightningnetwork/lightning-rfc/issues/791!
This is the only one, so I simply removed it.  We'd notice if a new field
was introduced which didn't change the output these days, but this has been
here since 2017.
Here's the difference in extract-formats.py's output:
```diff
@@ -177,6 +177,9 @@
msgtype,final_incorrect_htlc_amount,19
msgdata,final_incorrect_htlc_amount,incoming_htlc_amt,u64,
msgtype,channel_disabled,UPDATE|20
+msgdata,channel_disabled,flags,u16,
+msgdata,channel_disabled,len,u16,
+msgdata,channel_disabled,channel_update,byte,len
msgtype,expiry_too_far,21
msgtype,invalid_onion_payload,PERM|22
msgdata,invalid_onion_payload,type,bigsize,
```
=> BOLT 4: remove space in formatting which prevented tools/extract-formats.py

.aspell.en.pws, 02-peer-protocol.md, 09-features.md
In bitcoin 0.19.0, standardness rules are going to be relaxed to allow
future witness versions.  Once this is widely deployed, it will be safe
to accept them, smoothing use of future segwit versions.
See: https://github.com/bitcoin/bitcoin/pull/15846
=> BOLT 2: `option_shutdown_anysegwit` (Feature 26/27)

02-peer-protocol.md
We previously had a restriction on HTLC amounts to avoid big losses during the early phases of the network, but it shouldn't be necessary anymore.
As long as we honor `max_htlc_value_in_flight_msat` and implementations provide safe defaults for that parameter, we don't need that additional restriction.
I'm curious to know whether other implementations enforce this restriction or not (eclair doesn't).
=> Remove HTLC amount restriction

11-payment-encoding.md
Update Bolt 11 test vectors to always include a payment secret.
We want to make it mandatory in invoices which would make the existing test vectors invalid.
=> Make payment secret mandatory and update Bolt 11 test vectors

07-routing-gossip.md
This was missed in #877 (84213f45c05a39dd0812604a6a11d9d3c1207425).
As reported in https://github.com/ElementsProject/lightning/issues/4746
=> BOLT 7: remove 2^32 restriction from channel_update as well.

02-peer-protocol.md, 03-transactions.md, 05-onchain.md, 09-features.md
Extension to the anchor output format that hinders the fee siphoning attack described by @ariard in https://lists.linuxfoundation.org/pipermail/lightning-dev/2020-September/002796.html
The fix itself, making the HTLC second stage transactions zero fee, was proposed by @ariard in the same thread.
=> feature: define option_zero_htlc_tx_fee (feature 22/23)

02-peer-protocol.md
This is extracted from channel_upgrade (#868), but used for opening
negotiation as suggested by @roasbeef on the last spec meeting.
It's a trivial change, fully backwards compatible, but now each channel
has a channel_type, which defines its behavior, rather than an ad-hoc
set of "sticky" feature bits.  It also means both peers can *support* a
feature without endorsing it.
**Note**: `channel_type` reuses feature bits so it's trivial to know how to extend in future (e.g. option_simplified_update, option_taproot, etc).  It's not an arbitrary set of feature bits, there really are only 4 values currently defined!
(I'm tempted to make another commit which changes the rest of the text to refer explicitly to channel_type now).
=> BOLT 2: send channel_type in open/accept

02-peer-protocol.md
With anchor outputs, we can keep the commit tx feerate lower than the real on-chain feerate.
That means that when closing the channel, the closing fee will not necessarily be lower than the current commit tx fee, the existing requirement doesn't make sense to be that strict (at least for anchor outputs).
Imagine for example that the commitment feerate is kept at 10 sat/byte (what lnd currently does when using anchor outputs).
Imagine you want to do a mutual close on that channel and target a confirmation in N blocks, which results in a feerate higher than 10 sat/byte.
That's perfectly reasonable and should be allowed, otherwise you have no way of negotiating a feerate higher than 10 sat/byte (which may confirm in weeks if the mempool is quite full, like it is nowadays).
=> Update closing_signed fee requirement

01-messaging.md
It doesn't make sense to exchange amounts that exceed the total bitcoin supply, so let's make that an explicit requirement.
Eclair has always enforced this requirement at the wire layer, where messages that use invalid bitcoin amounts are automatically rejected.
=> Restrict bitcoin amounts

02-peer-protocol.md, 03-transactions.md
Since HTLCs below this amount will not appear in the commitment tx, they are effectively converted to miner fees. The peer could use this to grief you by broadcasting its commitment once it contains a lot of dust HTLCs.
I just stumbled upon issue #696 which mentioned that a while ago, but we didn't update the spec accordingly.
However, implementations do already enforce that.
I also added a lower bound on `dust_limit_satoshis` that ensures that transactions will correctly propagate with default relay policies.
Fixes #696 and #905
=> Peers need to check each other's dust limit

01-messaging.md
Should resolve https://github.com/lightning/bolts/issues/937 for quite a long while @t-bast
=> BOLT01: Switch  extension records to unknown fields in test vector

02-peer-protocol.md, 09-features.md
In this commit, we add a new feature bit to gate the new explicit
channel type funding via the new `channel_type` TLV. The addition of
this new bit allows peers to seek out other peers that understand the
new explicit channel negotiation. This is useful in practice, as it
allows peers to avoid needing to "downgrade" the feature bits advertised
at the connection level due to one peer not understanding a new
required feature bit while it has a channel with a connecting peer.
Such a workaround is already deployed on the network between lnd peers
and certain eclair peers, as the `lnd` peers require static key, but the
feature bit is unknown to eclair peers. This situation (forced
downgrade) is undesirable, as until the connected peer updates (or the
channel is closed) and "worst" feature bit …
=> BOLT-02+09: introduce feature bit to gate new channel_type feature - 44/45

07-routing-gossip.md
As per https://lists.linuxfoundation.org/pipermail/lightning-dev/2021-June/003044.html .
Advise to not include/ignore them in announcements. We could also just remove the addr type `3` entirely, since it's not supported by any up-to-date Tor software anymore.
=> gossip: deprecate Tor v2 onion services

01-messaging.md
There's not a lot of reason to explicitly rate-limit ping messages
on the sending side, hosts on the internet can *always* send you
as much traffic as they want, its up to you whether you want to
talk back to them.
This seems to have been intended as a cutoff where nodes can skip
responding to pings below a certain rate, but in practice 30
seconds is much too long a time to learn that your peer has
disconnected.
We could reduce the threshold, but its not like this is the only
place in the spec where a peer can request a message response, and
that is unlikely to change, making it of highly dubious value.
=> Drop ping sending rate-limit suggestion

00-introduction.md, 01-messaging.md, 02-peer-protocol.md, 03-transactions.md, 05-onchain.md, 07-routing-gossip.md
#834 got closed by a bad push, sorry...
This is the same, with a final fixup!
=> Really: BOLT 1: introduce warning messages, reduce requirements to send (hard) errors

04-onion-routing.md, 09-features.md, 11-payment-encoding.md
This PR adds a new field to bolt11 invoices for payment metadata. Senders are supposed to carry over this data to a tlv field to provide context for stateless invoice applications.
More background on stateless invoices: https://lists.linuxfoundation.org/pipermail/lightning-dev/2021-September/003236.html
_Please attach comments to the most appropriate line of the diff, so that discussions remain threaded and can eventually be resolved. We all know what PRs look like with too many top level comments._
=> Add payment metadata to payment request (feature 48)

02-peer-protocol.md, 09-features.md
Fixup changes:
* features: make anchor zero fee explicitly dependent on static key
* re-order section explaining new HTLC output trimming
=> anchors: follow up changes after initial zero fee anchors merge

05-onchain.md
Prior to the addition of `warning` messages, BOLT 5 specified a
few cases where users should be warned that funds may have been
lost. However, it used the phrasing "send a warning" which can now
be confused  with `warning` messages. Nodes should not generally
inform their counterparty that they have been robbed.
=> s/send a warning/warn the user/ in BOLT 5 to avoid confusion

01-messaging.md
This is an alternate approach to https://github.com/lightningnetwork/lightning-rfc/pull/911 (BOLT 7: add gossip address descriptor type DNS hostname)
relying less on centralized services (DNS, IP query sites, ...) to solve the issue
of detecting a nodes own public IPv4 behind a NAT.
This adds the option to report an remote IP address back to a connecting
peer using the `init` message. A node can decide to use that information
to discover a potential update to its public IPv4 address (NAT) and use
that for a `node_announcement` update message containg the new address.
The proposal includes reporting the IPv4 and IPv6 address,
however in IPv6 there are likely no NAT issues. TOR is skipped for
obvious reasons.
Certain appoaches to check and use this information are thinkable:
- Wait for …
=> BOLT 1: adds remote address to optional init_tlvs (IP discovery)

02-peer-protocol.md, 05-onchain.md
Following the discussion at #932 and looking at the proposal of #834 I thought it might be good to clarify in BOLT 5 when a node MUST NOT (potentially SHOULD NOT) broadcast its own commitment transaction when failing the channel. 
If a node has to fail a channel but knows that its latest commitment transaction is outdated it should not be required to send it but rather wait for the peer to unilaterally close the channel. 
The proposed solution is not so clean because it might produce a deadlock in which two peers assume they have outdated state and send `error` back and forth without actually force closing. Maybe in such a scenario we could create a protocol that mutually closes with split balance? 
Also replaced the word use with broadcast as it seems more accurate.
=> Removed requirement to broadcast an outdated commitment transaction

02-peer-protocol.md
Once #834 have been accepted to the spec, we should use a warning in quick close instead of failing the connection.
=> Use warning message in quick close

02-peer-protocol.md
One argument for adding a feature bit for channel types was to make things more explicit and remove ambiguity (the other main argument was to be able to filter out peers that don't support this feature).
When sending `open_channel`, we require funders to include a `channel_type`, so it would make sense to require fundees to echo that `channel_type` back to explicitly confirm that they're ok with this particular `channel_type`.
This is the current behavior of eclair, please let me know if other implementations are doing it differently, and if you think this additional requirement shouldn't be added.
=> Echo `channel_type` in `accept_channel`

07-routing-gossip.md
Gossip query compression is not very useful - it was added for
mobile clients to, in theory, sync the gossip data directly from
P2P peers, but to my knowledge no mobile clients actually use it
for that, or at least use it where the gossip *query* data is a
substantial portion of their overall bandwidth usage.
Further, because of the semantics of `gossip_timestamp_filter`, its
impractical to ensure you receive a reliable, full view of the
gossip data without re-downloading large portions of the gossip
data on startup.
Ultimately, gossip queries are a pretty non-optimal method of
synchronizing the gossip data. If someone wants highly optimized
gossip data synchronization a new method based on set
reconciliation needs to be propose.
Finally, the current gossip query encoding semantics do not …
=> Remove zlib compression gossip query support

01-messaging.md
It had a blank line and invalid format for tools/extract-formats.py.  This meant that the python package omitted it!
And move the format information into the requirements section
(and fix spelling: `node_announement` -> `node_announcement`
Diff for extract-formats.py before and after:
```diff
--- /tmp/before	2022-05-17 10:47:01.583086352 +0930
+++ /tmp/after	2022-05-17 10:51:59.166850111 +0930
@@ -6,6 +6,8 @@
msgdata,init,tlvs,init_tlvs,
tlvtype,init_tlvs,networks,1
tlvdata,init_tlvs,networks,chains,chain_hash,...
+tlvtype,init_tlvs,remote_addr,3
+tlvdata,init_tlvs,remote_addr,data,byte,...
msgtype,error,17
msgdata,error,channel_id,channel_id,
msgdata,error,len,u16,
```
=> BOLT 1: make remote_addr definition machine readable.

02-peer-protocol.md
This is a second proposal different from https://github.com/lightning/bolts/pull/976 where it is not allowed to send multiple shutdown messages from the receiver viewpoint.
The rationale for this is to avoid bad cases like the following one that is permitted by the spec
```
____________________________________________
| sender -> shutdown(script_one) -> receiver |
| sender -> shutdown(script_two) -> receiver |
| sender <- shutdown(script_one) <- receiver |
--------------------------------------------
```
=> BOLT 2: disallow sending multiple `shutdown` msg

01-messaging.md
This is an opinionate change proposed where there are reasons to have a default behavior for different networks, but there are also good reasons to have not this behavior.
I found the PR on Bitcoin core https://github.com/bitcoin/bitcoin/pull/23306 very good to have a good summary of pros and cons.
In addition, I think having a default port for different networks on lightning is a good thing to have because introducing some way to detect which network a lightning node is exposing with a particular URL composed by `node_id@ip:port`
We introduce a default behavior on c-lighting with the PR https://github.com/ElementsProject/lightning/pull/4900
P.S: As plus we have already a default port for Bitcoin maintet.
Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>
=> BOLT 1: introduce port convention for different network

07-routing-gossip.md
This is a follow-up on #1006, which actually created more confusion.
This is somewhat hard to explain both clearly and concisely, let me know if I should make it less concise and more clear.
See https://github.com/lightning/bolts/pull/1006#issuecomment-1200785218 for more context.
=> Clarify Bolt 7 latest channel update pruning

07-routing-gossip.md
Since #910, nodes are allowed to use aliases instead of real scids. It would be quite helpful to be explicit about it and set a flag in `channel_update` when an alias is used instead of a real scid for a few reasons:
- the receiving peer knows that this `channel_update` is meant to be kept private and can internally store it separately from "real" channel updates without requiring a lookup into an internal mapping table
- the sender knows whether they're using an alias or not, so it's trivial to set that bit
We also make the `htlc_maximum_msat` field mandatory: every node on the network currently sets it, so we can simplify message parsing. This makes this PR an alternative to #996
@cdecker @TheBlueMatt @crypt-iQ is that message flag helpful for your implementation's router logic?
DAMN I …
=> Bolt7: add channel update flag for scid alias

07-routing-gossip.md
Allows us time to propagate a splice update (new channel_announcement)
Suggested-By: @t-bast
Co-Authored: @ddustin
=> gossip: delay considering a channel edge deleted for 12-blocks

04-onion-routing.md
When a node retires a failed path as part of a larger MPP payment, the node may wish to use a path which is constrained by an `htlc_minimum_msat` value. In this case, the node is forced to overpay, likely overshooting the `total_msat` it set in the earlier onions for the same MPP payment.
There are two possible solutions to this - either allow the `total_msat` value to change in later HTLCs or allow the node to (slightly) overshoot the `total_msat` value.
Allowing `total_msat` to change across HTLCs is nontrivial to implement - HTLCs may arrive out-of-order, causing the receiving node to have to track all seen `total_msat` values and accept a set of HTLCs which meet any of the seen `total_msat` values.
Instead, this commit changes the MPP logic to simply allow a sender to overshoot the …
=> Allow nodes to overshoot the MPP `total_msat` when paying

02-peer-protocol.md, 04-onion-routing.md, 07-routing-gossip.md, 11-payment-encoding.md
When nodes receive HTLCs, they verify that the contents of those HTLCs match the intructions that the sender provided in the onion. It is important to ensure that intermediate nodes and final nodes have similar requirements, otherwise a malicious intermediate node could easily probe whether the next node is the final recipient or not.
Unfortunately, the requirements for intermediate nodes were more lenient than the requirements for final nodes. Intermediate nodes allowed overpaying and increasing the CLTV expiry, whereas final nodes required a perfect equality between the HTLC values and the onion values.
This provided a trivial way of probing: when relaying an HTLC, nodes could relay 1 msat more than what the onion instructed (or increase the outgoing expiry by 1). If the next node was …
=> Allow nodes to overshoot final htlc amount and expiry

04-onion-routing.md
The sender chooses the amounts that are set in the onion payload (`amt_to_forward`) but cannot predict what amounts will be set in the HTLCs (`amount_msat`) since intermediate nodes are allowed to overpay.
This was pointed out by @joostjager [here](https://github.com/lightning/bolts/pull/1031#discussion_r1016479991).
=> Use onion amount in MPP set calculation

11-payment-encoding.md
Make it more obvious to readers of bolt 11 that the maximum length of a Tagged Field is 639 bytes.
=> a note on the maximum size of Tagged Fields

04-onion-routing.md
In #1032 we allowed overshooting the final amount and expiry, but forgot to update the onion error descriptions which make reference thereto.
=> Update onion errors since we allow overpaying or under-CLTVing

01-messaging.md
The sentence `..., leading zeros in integers can be omitted` in the Bolt 1 fundamental type section: https://github.com/lightning/bolts/blob/50b2df24a27879e8329712c275db78876fd022fe/01-messaging.md#fundamental-types imposes that it is not necessary, but optional to truncate leading zeros in `tuXX` fields.
Having a look at the `tuXX` parsers across the ln implementations, it seems that it is expected to omit leading zeros.
This PR tries to find a better explanation/definition to avoid uncertainties.
=> Bolt 1: Clarify the definition of tu fields

07-routing-gossip.md
Bolt 7 specifies _how_ to set `hltc_minimum_msat`  and `htlc_maximum_msat` but does not explicitly enforce `hltc_minimum_msat` <= `htlc_maximum_msat`.
Since a channel where the largest HTLC that the advertising node will send through it is smaller than the minimum value the peer will accept is unusable, it seems reasonable to blacklist this type of gossip?
=> bolt07: enforce htlc_maximum_msat >= htlc_minimum_msat

08-transport.md
lnmessage got this wrong!  It would pass our test vectors, but actually fail in real usage, since it used the same `ck`.
Also, nonce rotation happens after 1000 encryptions, which is when the nonce reaches 1000 (since it's zero based!), not when it *exceeds* 1000.
=> BOLT 8: make it clear that there are *two* chaining keys.

02-peer-protocol.md
In most cases the `onion_hash` isn't actionable in the case of blinded payments and it's wasteful to keep track of the incoming onion, so we allow setting it to an all zero value.
=> Allow unset `onion_hash` in `invalid_onion_blinding`

04-onion-routing.md
This PR replaces #1066, picking this up as discussed in the spec meeting!
Senders making payments to a blinded route know the total `cltv_delta` for the blinded portion of the route, but not the `min_final_cltv_delta` for the final hop. This PR updates the instructions for the sender to set the final hop's `outgoing_cltv_detla` to `current_height + any random offset added`.
See [gist](https://gist.github.com/t-bast/b1371d357a2c5f3e8c09514a62db7079) for additional context.
=> Blinded Paths: clarify outgoing_cltv_value for final hop

11-payment-encoding.md
If the requirement is that a writer MUST include `c`, how come that the examples not all have `c`?
should there be a `c` in the examples? 
or is it really a MAY?
ran into this by implementing that writer exception and running the testsuite through the examples.
am i misunderstanding something?
thanks for the review.
=> [QUESTION] bolt11: A writer MUST include "c" but not in examples

09-features.md
While reviewing a patch on lnprototest, I encountered a scenario where the BOLT 9 specification needed to provide clear guidance.
As a result, this commit adds specific requirements to determine the appropriate behaviour when a node specifies both optional and required features.
Additionally, if this situation appears to be an
implementation bug, it will be taken care of accordingly.
Reported-by: lnprototest
=> bol09: Specify behavior when a node specifies both optional and required features

02-peer-protocol.md
Since "reject" isn't defined anywhere in the spec and "fail" does have a definition laid out in BOLT1 that includes special provisions for channels that have not yet been established, BOLT2 is amended to clarify the requirements for the receiver of `accept_channel`
=> BOLT2: change "reject" to "fail" in channel opening requirements

CONTRIBUTING.md
1. Put it in the PR title so everyone can see.
2. Deploy with +100 while it's still unratified, in case it changes.
=> CONTRIBUTING.md: modern feature bit assignment.

02-peer-protocol.md
Prior wording of the description of this parameter left room for ambiguity around whether it capped the total value offered by both channel peers combined or if it was solely capping the total value of HTLCs offered by the remote.
=> Clarify the semantics of `max_htlc_value_in_flight_msat`

01-messaging.md
i.e. it was present in the init feature bits.  We use this in several places, but assume everyone knows what it means.
It's particularly fraught with required features: it's explicitly legitimate to assume these are accepted if the node keeps talking to you after init!
=> BOLT 1: define what `offered` and `negotiated` mean.

04-onion-routing.md
Currently BOLT#4 recommends to forwarding node to reject HTLC with `nLocktime` field to far in the future from chain tip height (type 21: `expiry_too_far`). This recommendation is reasonable to avoid liquidity griefing where a HTLC would be send so far in the future (e.g 20 000 blocks from chain tip), than in case of on-chain force-closure of the link, the forwarding node cannot confirm the HTLC-timeout and therefore recover the satoshis locked.
I think this recommendation is implemented by all the main Lightning implementations. For e.g, for LDK will reject HTLC more than 2016 block in the future (`CLTV_FAR_FAR_AWAY`). This comes with few downsides, a) a payer cannot build payment path with more than 14 hops requesting at least a `cltv_expiry_delta` of 144 blocks, such path while onerous …
=> BOLT4: Specify max HTLC nLocktime for expiry_too_far

proposals/route-blinding.md
Payment recipients must ensure that they have a few blocks before fulfilling the payment, in case the inbound channel force-closes.
=> Add `min_final_expiry_delta` to blinded route example

01-messaging.md
The documentation incorrectly listed the hexadecimal value of the Signet port as 0xF87 when it should be 0x9B77. This commit updates the port to the correct hexadecimal representation.
=> Fix incorrect hex value for Signet port in BOLT #1

04-onion-routing.md
I always get this wrong too, so CLN actually has a source check for this, and it triggered when importing the latest spec!
=> BOLT 4: It's Check Lock Time Verify not Check Time Lock Verify.

07-routing-gossip.md
According to BOLT 11, the default `min_final_cltv_expiry_delta` is 18, not 9.
=> BOLT 7: correct the default `min_final_cltv_expiry_delta` in routing example

04-onion-routing.md
In this commit, we propose a purely syntactical change to the current blinded paths specification. Rather than denote the public key of the i-th node as `E(i)`, we propose that instead it's denoted as: `E_i`. This results in less overall characters, and is more similar to notation customarily used in LaTeX.
My personal preference is that the proposed notation is easier to scan at a glance, and also less ambiguous (doesn't look like a function call).
=> BOLT-04: use underscores in place of parens for blinded paths notation

07-routing-gossip.md
We introduced a 12-blocks delay for channel closing in #1004, but we didn't update the requirement in the section about pruning. This is just a follow-up on that PR.
@niftynei @TheBlueMatt @rustyrussell
=> gossip: 12-blocks delay channel closed follow-up

.aspell.en.pws, 02-peer-protocol.md, 09-features.md
A simple protocol for upgrades, splices and other things which are easier when no updates are in-flight.
=> BOLT 2: quiescence protocol (feature 34/35) option_quiesce

04-onion-routing.md
Fixes https://github.com/lightning/bolts/issues/1125
=> BOLT04: Add rationale for constant error decryption.

04-onion-routing.md
As noted previously, `channel_update`s in the onion failure packets are massive gaping fingerprintign vulnerabilities - if a node applies them in a publicly-visible way the err'ing node can easily identify the sender of an HTLC.
While the updates are still arguably marginally useful for nodes to use in their pathfinding local to retires of the same payment, this too will eventually become an issue with PTLCs. Further, we shouldn't be letting nodes get away with delaying payments by failing to announce the latest channel parameters or enforcing new parameters too soon, so treating the node as having indicated insufficient liquidity (or other general failure) is appropriate in the general case.
Thus, here, we begin phasing out the `channel_update` field, requiring nodes ignore it outside of …
=> Drop the required `channel_update` in failure onions

04-onion-routing.md, proposals/route-blinding.md
- This PR adds some clarification in BOLT 4 around how to calculate the `max_ctlv_expiry` that is added to the `payment_constraints` field for
hops in a blinded path. 
- It also adds a formula for calculating the total 
blinded path cltv delta so that it is clear that this should include the `min_final_cltv_expiry_delta`. 
- Finally, the route blinding payments example in the proposals doc is
fixed so that the correct `max_cltv_expiry` is included in the final 
hop's payload. 
Fixes https://github.com/lightning/bolts/issues/1174
The one other thing from #1174 that I didnt cover here was re the shadow route suggestions: for blinded paths. See comment [here](https://github.com/lightning/bolts/issues/1174#issuecomment-2189795809) for more details. If it is agreed that it no longer makes …
=> bolt4+proposals: fix `max_cltv_expiry` calculation

bolt12/offers-test.json, proposals/route-blinding.md
We renamed `blinding` to `path_key` in #1181, but forgot to update the description in test vectors and the proposal document.
=> Leftover renaming of `path_key` in blinded paths

01-messaging.md, 09-features.md
This pull request proposes peer storage, inspired by @t-bast's [peer backup storage](https://github.com/lightning/bolts/pull/881). We create two separate messages, which users can use to distribute encrypted 'blobs' of up to 64 KB to their peers.
Users can distribute a 'blob' and update it whenever their configuration changes by sending a 'peer_storage' message. In return, they will always receive a 'your_peer_storage' message, which will serve as an acknowledgment.
Nodes can also decide whether they want to provide this service in exchange for some sats.
You can check out the implementation in CLN [here](https://github.com/ElementsProject/lightning/pull/5361)
Thank you so much, @rustyrussell, for all the help and guidance!
=> Peer storage for nodes to distribute small encrypted blobs.

00-introduction.md, 12-offer-encoding.md
=> meta: indexing the bolt12
